<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AgencyTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $agencyTypes = [
            [
                'name' => 'Recruiting Agency',
                'slug' => 'recruiting-agency',
                'icon' => 'users',
                'color' => 'blue',
                'description' => 'International manpower recruitment and placement services for overseas employment',
                'allowed_service_modules' => json_encode([3, 18, 19, 20, 21, 22]), // Work Visa + All Job services
                'required_certifications' => json_encode(['BMET License', 'RL License']),
                'default_commission_rate' => 15.00,
                'min_commission_rate' => 10.00,
                'max_commission_rate' => 20.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => true,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'name' => 'Student Consultancy',
                'slug' => 'student-consultancy',
                'icon' => 'academic-cap',
                'color' => 'indigo',
                'description' => 'Study abroad consultancy for university admissions and student visa processing',
                'allowed_service_modules' => json_encode([2, 14, 15, 16, 17]), // Student Visa + All Education services
                'required_certifications' => json_encode(['Education Consultancy License']),
                'default_commission_rate' => 18.00,
                'min_commission_rate' => 15.00,
                'max_commission_rate' => 25.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => true,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'name' => 'Language Center',
                'slug' => 'language-center',
                'icon' => 'language',
                'color' => 'purple',
                'description' => 'IELTS, TOEFL, and language proficiency training with test preparation',
                'allowed_service_modules' => json_encode([16, 23]), // Language Test + Translation
                'required_certifications' => json_encode(['IELTS Partnership', 'Training Center License']),
                'default_commission_rate' => 12.00,
                'min_commission_rate' => 8.00,
                'max_commission_rate' => 15.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => false,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'name' => 'File Processing Center',
                'slug' => 'file-processing-center',
                'icon' => 'folder-open',
                'color' => 'green',
                'description' => 'Complete visa file preparation and document processing for all visa types',
                'allowed_service_modules' => json_encode([1, 2, 3, 4, 5, 6, 7, 23, 24, 25, 26, 27]), // All Visas + All Documents
                'required_certifications' => json_encode(['Document Processing License', 'Notary Authorization']),
                'default_commission_rate' => 10.00,
                'min_commission_rate' => 8.00,
                'max_commission_rate' => 15.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => false,
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'name' => 'Skill Training Institute',
                'slug' => 'skill-training-institute',
                'icon' => 'wrench-screwdriver',
                'color' => 'orange',
                'description' => 'Technical and vocational skill training for overseas employment preparation',
                'allowed_service_modules' => json_encode([16, 20, 21]), // Language Test + Interview Prep + Skill Verification
                'required_certifications' => json_encode(['BTEB Approval', 'Training Institute License']),
                'default_commission_rate' => 15.00,
                'min_commission_rate' => 10.00,
                'max_commission_rate' => 20.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => false,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'name' => 'Work Permit Agency',
                'slug' => 'work-permit-agency',
                'icon' => 'document-check',
                'color' => 'teal',
                'description' => 'Specialized work permit and employment visa processing services',
                'allowed_service_modules' => json_encode([3, 22]), // Work Visa + Work Permit Processing
                'required_certifications' => json_encode(['Work Permit License', 'Immigration Consultant License']),
                'default_commission_rate' => 16.00,
                'min_commission_rate' => 12.00,
                'max_commission_rate' => 22.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => true,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'name' => 'Medical/GAMCA Agent',
                'slug' => 'medical-gamca-agent',
                'icon' => 'heart',
                'color' => 'red',
                'description' => 'Medical examination coordination for GAMCA and visa medical requirements',
                'allowed_service_modules' => json_encode([5, 31]), // Medical Visa + Medical Certificate
                'required_certifications' => json_encode(['GAMCA Authorization', 'Medical Center License']),
                'default_commission_rate' => 10.00,
                'min_commission_rate' => 8.00,
                'max_commission_rate' => 15.00,
                'can_set_own_pricing' => false,
                'requires_verification' => true,
                'requires_insurance' => true,
                'can_manage_team' => false,
                'can_create_resources' => false,
                'needs_country_assignment' => false,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'name' => 'Hajj-Umrah Agency',
                'slug' => 'hajj-umrah-agency',
                'icon' => 'globe-alt',
                'color' => 'emerald',
                'description' => 'Complete Hajj and Umrah packages with visa, flights, accommodation, and guidance',
                'allowed_service_modules' => json_encode([28, 8, 9, 10]), // Hajj & Umrah + Flight + Hotel + Insurance
                'required_certifications' => json_encode(['Hajj License', 'Ministry of Religious Affairs Approval']),
                'default_commission_rate' => 12.00,
                'min_commission_rate' => 10.00,
                'max_commission_rate' => 18.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => true,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => false,
                'is_active' => true,
                'display_order' => 8,
            ],
            [
                'name' => 'Visa Documentation Agency',
                'slug' => 'visa-documentation-agency',
                'icon' => 'document-text',
                'color' => 'blue',
                'description' => 'Visa application documentation and embassy submission services',
                'allowed_service_modules' => json_encode([1, 2, 3, 4, 5, 6, 7, 23, 24]), // All Visas + Translation + Attestation
                'required_certifications' => json_encode(['Visa Processing License']),
                'default_commission_rate' => 14.00,
                'min_commission_rate' => 10.00,
                'max_commission_rate' => 20.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => true,
                'is_active' => true,
                'display_order' => 9,
            ],
            [
                'name' => 'Notary/Attestation Desk',
                'slug' => 'notary-attestation-desk',
                'icon' => 'stamp',
                'color' => 'gray',
                'description' => 'Document attestation, notarization, and official certification services',
                'allowed_service_modules' => json_encode([24, 25, 26, 27]), // All Document services
                'required_certifications' => json_encode(['Notary Public License', 'Attestation Authorization']),
                'default_commission_rate' => 8.00,
                'min_commission_rate' => 5.00,
                'max_commission_rate' => 12.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => false,
                'can_create_resources' => false,
                'needs_country_assignment' => false,
                'is_active' => true,
                'display_order' => 10,
            ],
            [
                'name' => 'Travel Agency',
                'slug' => 'travel-agency',
                'icon' => 'airplane',
                'color' => 'sky',
                'description' => 'Flight booking, hotel reservations, and complete travel package services',
                'allowed_service_modules' => json_encode([1, 8, 9, 10, 11, 12, 13, 28]), // Tourist Visa + All Travel services + Hajj
                'required_certifications' => json_encode(['IATA License', 'Travel Agency License']),
                'default_commission_rate' => 10.00,
                'min_commission_rate' => 8.00,
                'max_commission_rate' => 15.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => true,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => false,
                'is_active' => true,
                'display_order' => 11,
            ],
            [
                'name' => 'Travel Insurance Agent',
                'slug' => 'travel-insurance-agent',
                'icon' => 'shield-check',
                'color' => 'cyan',
                'description' => 'Travel insurance coverage for visa applications and international travel',
                'allowed_service_modules' => json_encode([10]), // Travel Insurance only
                'required_certifications' => json_encode(['Insurance Agent License']),
                'default_commission_rate' => 20.00,
                'min_commission_rate' => 15.00,
                'max_commission_rate' => 30.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => true,
                'can_manage_team' => false,
                'can_create_resources' => false,
                'needs_country_assignment' => false,
                'is_active' => true,
                'display_order' => 12,
            ],
            [
                'name' => 'International Cargo Agent',
                'slug' => 'international-cargo-agent',
                'icon' => 'truck',
                'color' => 'amber',
                'description' => 'International shipping and cargo services for personal and commercial goods',
                'allowed_service_modules' => json_encode([]), // Custom services, not in standard modules
                'required_certifications' => json_encode(['Cargo License', 'Customs Clearance License']),
                'default_commission_rate' => 8.00,
                'min_commission_rate' => 5.00,
                'max_commission_rate' => 12.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => true,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => false,
                'is_active' => true,
                'display_order' => 13,
            ],
            [
                'name' => 'Settlement Support Service',
                'slug' => 'settlement-support-service',
                'icon' => 'home',
                'color' => 'lime',
                'description' => 'Post-arrival settlement assistance including accommodation, banking, and integration',
                'allowed_service_modules' => json_encode([29, 32, 33, 34, 35, 36, 37, 38]), // All Support services
                'required_certifications' => json_encode(['Settlement Service License']),
                'default_commission_rate' => 12.00,
                'min_commission_rate' => 10.00,
                'max_commission_rate' => 18.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => true,
                'is_active' => true,
                'display_order' => 14,
            ],
            [
                'name' => 'Skilled Migration Consultancy',
                'slug' => 'skilled-migration-consultancy',
                'icon' => 'chart-bar',
                'color' => 'violet',
                'description' => 'Points-based skilled migration consultation for Canada, Australia, New Zealand',
                'allowed_service_modules' => json_encode([3, 21, 22]), // Work Visa + Skill Verification + Work Permit
                'required_certifications' => json_encode(['MARA License (Australia)', 'ICCRC License (Canada)', 'Immigration Advisor License']),
                'default_commission_rate' => 20.00,
                'min_commission_rate' => 15.00,
                'max_commission_rate' => 30.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => true,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => true,
                'is_active' => true,
                'display_order' => 15,
            ],
            [
                'name' => 'CV & Job Application Agency',
                'slug' => 'cv-job-application-agency',
                'icon' => 'document-duplicate',
                'color' => 'pink',
                'description' => 'Professional CV writing, job search, and application assistance services',
                'allowed_service_modules' => json_encode([18, 19, 20]), // Job Posting + CV Builder + Interview Prep
                'required_certifications' => json_encode(['Career Counseling License']),
                'default_commission_rate' => 10.00,
                'min_commission_rate' => 8.00,
                'max_commission_rate' => 15.00,
                'can_set_own_pricing' => true,
                'requires_verification' => false,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => false,
                'is_active' => true,
                'display_order' => 16,
            ],
            [
                'name' => 'Translation Agency',
                'slug' => 'translation-agency',
                'icon' => 'language',
                'color' => 'rose',
                'description' => 'Certified translation services for all visa and official documents',
                'allowed_service_modules' => json_encode([23]), // Translation Services only
                'required_certifications' => json_encode(['Translator License', 'Language Institute License']),
                'default_commission_rate' => 15.00,
                'min_commission_rate' => 10.00,
                'max_commission_rate' => 25.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => false,
                'is_active' => true,
                'display_order' => 17,
            ],
            [
                'name' => 'HR Outsourcing Firm',
                'slug' => 'hr-outsourcing-firm',
                'icon' => 'briefcase',
                'color' => 'indigo',
                'description' => 'Complete HR solutions for international recruitment and employee management',
                'allowed_service_modules' => json_encode([18, 19, 20, 21, 22]), // All Employment services
                'required_certifications' => json_encode(['HR Consultancy License', 'Manpower License']),
                'default_commission_rate' => 18.00,
                'min_commission_rate' => 15.00,
                'max_commission_rate' => 25.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => true,
                'is_active' => true,
                'display_order' => 18,
            ],
            [
                'name' => 'Document Verification Agency',
                'slug' => 'document-verification-agency',
                'icon' => 'finger-print',
                'color' => 'slate',
                'description' => 'Background checks, document authentication, and credential verification',
                'allowed_service_modules' => json_encode([21, 24, 25]), // Skill Verification + Document Attestation + Police Clearance
                'required_certifications' => json_encode(['Verification Service License', 'Background Check Authorization']),
                'default_commission_rate' => 12.00,
                'min_commission_rate' => 10.00,
                'max_commission_rate' => 18.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => false,
                'can_create_resources' => false,
                'needs_country_assignment' => false,
                'is_active' => true,
                'display_order' => 19,
            ],
            [
                'name' => 'Cultural Exchange Agency',
                'slug' => 'cultural-exchange-agency',
                'icon' => 'user-group',
                'color' => 'fuchsia',
                'description' => 'Cultural exchange programs, internships, and educational exchanges',
                'allowed_service_modules' => json_encode([2, 37]), // Student Visa + Cultural Integration Support
                'required_certifications' => json_encode(['Cultural Exchange License', 'Education Program License']),
                'default_commission_rate' => 10.00,
                'min_commission_rate' => 8.00,
                'max_commission_rate' => 15.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => true,
                'is_active' => true,
                'display_order' => 20,
            ],
            [
                'name' => 'Caregiver Training + Placement',
                'slug' => 'caregiver-training-placement',
                'icon' => 'heart',
                'color' => 'red',
                'description' => 'Specialized caregiver training and international placement services',
                'allowed_service_modules' => json_encode([3, 16, 20, 22]), // Work Visa + Language Test + Interview Prep + Work Permit
                'required_certifications' => json_encode(['Caregiver Training License', 'Healthcare Training License']),
                'default_commission_rate' => 15.00,
                'min_commission_rate' => 12.00,
                'max_commission_rate' => 22.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => true,
                'is_active' => true,
                'display_order' => 21,
            ],
            [
                'name' => 'Work-Study Program Agency',
                'slug' => 'work-study-program-agency',
                'icon' => 'academic-cap',
                'color' => 'blue',
                'description' => 'Combined education and work programs for international students',
                'allowed_service_modules' => json_encode([2, 3, 14, 15, 16, 22]), // Student + Work Visa + Education services + Language Test + Work Permit
                'required_certifications' => json_encode(['Education Consultancy License', 'Work Permit License']),
                'default_commission_rate' => 16.00,
                'min_commission_rate' => 12.00,
                'max_commission_rate' => 22.00,
                'can_set_own_pricing' => true,
                'requires_verification' => true,
                'requires_insurance' => false,
                'can_manage_team' => true,
                'can_create_resources' => true,
                'needs_country_assignment' => true,
                'is_active' => true,
                'display_order' => 22,
            ],
        ];

        foreach ($agencyTypes as $type) {
            DB::table('agency_types')->insert(array_merge($type, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
