<?php

namespace Database\Seeders;

use App\Models\CvTemplate;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CvTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing templates safely (database agnostic)
        CvTemplate::query()->delete();
        
        $templates = [
            // FREE FOR ALL - No requirements
            [
                'name' => 'Basic Starter',
                'slug' => 'basic-clean',
                'description' => 'Completely free CV template for everyone. Simple, clean layout perfect for getting started quickly.',
                'preview_image' => 'cv-templates/basic-clean-preview.jpg',
                'category' => 'minimalist',
                'price' => 0.00,
                'can_purchase_with_points' => true,
                'points_required' => 0,
                'min_profile_completion' => 0,
                'features' => ['100% Free', 'No Requirements', 'Simple Layout', 'ATS-Friendly'],
                'layout_type' => 'single-column',
                'color_scheme' => 'gray',
                'file_path' => 'cv.templates.basic-clean',
                'is_active' => true,
                'sort_order' => 0,
            ],
            
            // FREE with Points - Entry Level (100 points, 80% completion)
            [
                'name' => 'Simple Professional',
                'slug' => 'simple-professional',
                'description' => 'Clean and minimalist CV template perfect for fresh graduates and entry-level professionals. ATS-friendly format.',
                'preview_image' => 'cv-templates/simple-professional-preview.jpg',
                'category' => 'professional',
                'price' => 200.00,
                'can_purchase_with_points' => true,
                'points_required' => 100,
                'min_profile_completion' => 80,
                'features' => ['ATS-Friendly', 'One Page', 'Simple Layout'],
                'layout_type' => 'single-column',
                'color_scheme' => 'black',
                'file_path' => 'cv.templates.simple-professional',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Minimalist Elite',
                'slug' => 'minimalist-elite',
                'description' => 'Ultra-clean design with maximum readability. Less is more approach for confident professionals.',
                'preview_image' => 'cv-templates/minimalist-elite-preview.jpg',
                'category' => 'minimalist',
                'price' => 280.00,
                'can_purchase_with_points' => true,
                'points_required' => 120,
                'min_profile_completion' => 85,
                'features' => ['Ultra Clean', 'Minimalist', 'One Page', 'Modern'],
                'layout_type' => 'single-column',
                'color_scheme' => 'gray',
                'file_path' => 'cv.templates.minimalist-elite',
                'is_active' => true,
                'sort_order' => 2,
            ],

            // PAID Templates (৳200-৳500)
            [
                'name' => 'Modern Professional',
                'slug' => 'modern-professional',
                'description' => 'Contemporary design with professional styling. Perfect for corporate jobs and experienced professionals.',
                'preview_image' => 'cv-templates/modern-professional-preview.jpg',
                'category' => 'professional',
                'price' => 250.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 70,
                'features' => ['ATS-Friendly', '2 Pages', 'Blue Theme', 'Professional'],
                'layout_type' => 'two-column',
                'color_scheme' => 'blue',
                'file_path' => 'cv.templates.modern-professional',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Creative Designer',
                'slug' => 'creative-designer',
                'description' => 'Bold and colorful template for creative professionals. Stand out from the crowd with unique styling.',
                'preview_image' => 'cv-templates/creative-designer-preview.jpg',
                'category' => 'creative',
                'price' => 300.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 75,
                'features' => ['Colorful', '2 Pages', 'Creative Layout', 'Portfolio Showcase'],
                'layout_type' => 'sidebar',
                'color_scheme' => 'multicolor',
                'file_path' => 'cv.templates.creative-designer',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Corporate Executive',
                'slug' => 'corporate-executive',
                'description' => 'Elegant template for senior positions and executives. Professional and sophisticated design.',
                'preview_image' => 'cv-templates/corporate-executive-preview.jpg',
                'category' => 'corporate',
                'price' => 350.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['Executive Style', '2 Pages', 'Professional', 'Leadership Focus'],
                'layout_type' => 'two-column',
                'color_scheme' => 'navy',
                'file_path' => 'cv.templates.corporate-executive',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'IT Developer Pro',
                'slug' => 'it-developer-pro',
                'description' => 'Tech-focused CV template highlighting skills and projects. Perfect for software developers and IT professionals.',
                'preview_image' => 'cv-templates/it-developer-pro-preview.jpg',
                'category' => 'professional',
                'price' => 300.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 80,
                'features' => ['Skills Section', 'Projects Showcase', 'Tech Stack', '2 Pages'],
                'layout_type' => 'two-column',
                'color_scheme' => 'green',
                'file_path' => 'cv.templates.it-developer-pro',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Healthcare Professional',
                'slug' => 'healthcare-professional',
                'description' => 'Specialized template for doctors, nurses, and healthcare workers. Emphasizes certifications and experience.',
                'preview_image' => 'cv-templates/healthcare-professional-preview.jpg',
                'category' => 'specialized',
                'price' => 350.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['Medical Focus', 'Certifications', 'Professional', '2 Pages'],
                'layout_type' => 'single-column',
                'color_scheme' => 'teal',
                'file_path' => 'cv.templates.healthcare-professional',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'International Format',
                'slug' => 'international-format',
                'description' => 'Global standard CV format for international job applications. Compatible with worldwide ATS systems.',
                'preview_image' => 'cv-templates/international-format-preview.jpg',
                'category' => 'professional',
                'price' => 400.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 90,
                'features' => ['International Standard', 'ATS-Friendly', '2 Pages', 'Global Format'],
                'layout_type' => 'single-column',
                'color_scheme' => 'black',
                'file_path' => 'cv.templates.international-format',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Premium Executive',
                'slug' => 'premium-executive',
                'description' => 'Top-tier template for C-level executives and senior management. Sophisticated and commanding presence.',
                'preview_image' => 'cv-templates/premium-executive-preview.jpg',
                'category' => 'corporate',
                'price' => 500.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 95,
                'features' => ['Premium Design', 'Executive Level', '3 Pages', 'Leadership Focus'],
                'layout_type' => 'two-column',
                'color_scheme' => 'gold',
                'file_path' => 'cv.templates.premium-executive',
                'is_active' => true,
                'sort_order' => 10,
            ],

            // NEW TEMPLATES (5 Additional Designs)
            [
                'name' => 'Elegant Two Column',
                'slug' => 'elegant-two-column',
                'description' => 'Sophisticated two-column layout with gradient sidebar. Perfect for professionals seeking an elegant presentation.',
                'preview_image' => 'cv-templates/elegant-two-column-preview.jpg',
                'category' => 'modern',
                'price' => 320.00,
                'can_purchase_with_points' => true,
                'points_required' => 150,
                'min_profile_completion' => 85,
                'features' => ['Gradient Design', 'Two Column', 'Elegant Typography', 'Skill Bars'],
                'layout_type' => 'two-column',
                'color_scheme' => 'purple',
                'file_path' => 'cv.templates.elegant-two-column',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Vibrant Modern',
                'slug' => 'vibrant-modern',
                'description' => 'Eye-catching colorful design with gradient accents. Stand out with a bold, modern presentation.',
                'preview_image' => 'cv-templates/vibrant-modern-preview.jpg',
                'category' => 'creative',
                'price' => 350.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 80,
                'features' => ['Vibrant Colors', 'Modern Design', 'Gradient Backgrounds', 'Skill Cards'],
                'layout_type' => 'single-column',
                'color_scheme' => 'orange',
                'file_path' => 'cv.templates.vibrant-modern',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Academic Research',
                'slug' => 'academic-research',
                'description' => 'Formal template designed for academics, researchers, and scholars. Emphasizes publications and research output.',
                'preview_image' => 'cv-templates/academic-research-preview.jpg',
                'category' => 'professional',
                'price' => 380.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 90,
                'features' => ['Academic Format', 'Publications Section', 'Research Focus', 'Professional Typography'],
                'layout_type' => 'single-column',
                'color_scheme' => 'black',
                'file_path' => 'cv.templates.academic-research',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Sales & Marketing',
                'slug' => 'sales-marketing',
                'description' => 'Dynamic template for sales and marketing professionals. Highlights achievements and metrics with visual impact.',
                'preview_image' => 'cv-templates/sales-marketing-preview.jpg',
                'category' => 'professional',
                'price' => 340.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['Achievement Metrics', 'Bold Design', 'Two Column', 'Results Focused'],
                'layout_type' => 'two-column',
                'color_scheme' => 'red',
                'file_path' => 'cv.templates.sales-marketing',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Designer Portfolio',
                'slug' => 'designer-portfolio',
                'description' => 'Creative portfolio-style CV for designers and creatives. Showcases work with a modern, minimalist aesthetic.',
                'preview_image' => 'cv-templates/designer-portfolio-preview.jpg',
                'category' => 'creative',
                'price' => 420.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 90,
                'features' => ['Portfolio Grid', 'Modern Design', 'Black Theme', 'Creative Layout'],
                'layout_type' => 'grid',
                'color_scheme' => 'black',
                'file_path' => 'cv.templates.designer-portfolio',
                'is_active' => true,
                'sort_order' => 15,
            ],
            
            // Additional Specialized Templates (16-30)
            [
                'name' => 'Tech Specialist',
                'slug' => 'tech-specialist',
                'description' => 'Technology specialist template with modern design. Perfect for IT professionals and technical roles.',
                'preview_image' => 'cv-templates/tech-specialist-preview.jpg',
                'category' => 'professional',
                'price' => 320.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 80,
                'features' => ['Technical Skills', 'Project Showcase', 'Modern Design'],
                'layout_type' => 'two-column',
                'color_scheme' => 'blue',
                'file_path' => 'cv.templates.tech-specialist',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Finance Executive',
                'slug' => 'finance-executive',
                'description' => 'Professional template for finance professionals and executives. Emphasizes analytical skills and achievements.',
                'preview_image' => 'cv-templates/finance-executive-preview.jpg',
                'category' => 'corporate',
                'price' => 420.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 90,
                'features' => ['Finance Focus', 'Professional', 'Achievement Oriented'],
                'layout_type' => 'two-column',
                'color_scheme' => 'navy',
                'file_path' => 'cv.templates.finance-executive',
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Medical Professional',
                'slug' => 'medical-professional',
                'description' => 'Comprehensive medical CV template for doctors and medical practitioners. Highlights qualifications and experience.',
                'preview_image' => 'cv-templates/medical-professional-preview.jpg',
                'category' => 'specialized',
                'price' => 380.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 90,
                'features' => ['Medical Focus', 'Detailed Sections', 'Professional'],
                'layout_type' => 'two-column',
                'color_scheme' => 'teal',
                'file_path' => 'cv.templates.medical-professional',
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'name' => 'Legal Counsel',
                'slug' => 'legal-counsel',
                'description' => 'Professional template for lawyers and legal professionals. Emphasizes education, cases, and bar admissions.',
                'preview_image' => 'cv-templates/legal-counsel-preview.jpg',
                'category' => 'specialized',
                'price' => 400.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 90,
                'features' => ['Legal Focus', 'Case Highlights', 'Professional'],
                'layout_type' => 'two-column',
                'color_scheme' => 'navy',
                'file_path' => 'cv.templates.legal-counsel',
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'name' => 'Engineer Technical',
                'slug' => 'engineer-technical',
                'description' => 'Engineering-focused CV template highlighting technical skills and projects. Perfect for engineers and technical professionals.',
                'preview_image' => 'cv-templates/engineer-technical-preview.jpg',
                'category' => 'specialized',
                'price' => 340.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['Technical Skills', 'Project Focus', 'Engineering'],
                'layout_type' => 'two-column',
                'color_scheme' => 'blue',
                'file_path' => 'cv.templates.engineer-technical',
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'name' => 'Architect Planner',
                'slug' => 'architect-planner',
                'description' => 'Specialized template for architects and urban planners. Showcases projects and design philosophy.',
                'preview_image' => 'cv-templates/architect-planner-preview.jpg',
                'category' => 'specialized',
                'price' => 360.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['Architecture Focus', 'Project Showcase', 'Visual'],
                'layout_type' => 'grid',
                'color_scheme' => 'gray',
                'file_path' => 'cv.templates.architect-planner',
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'name' => 'Data Scientist',
                'slug' => 'data-scientist',
                'description' => 'Data science professional template emphasizing technical skills, projects, and analytical capabilities.',
                'preview_image' => 'cv-templates/data-scientist-preview.jpg',
                'category' => 'specialized',
                'price' => 380.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['Data Focus', 'Technical Skills', 'Project Based'],
                'layout_type' => 'two-column',
                'color_scheme' => 'purple',
                'file_path' => 'cv.templates.data-scientist',
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'name' => 'HR Specialist',
                'slug' => 'hr-specialist',
                'description' => 'Human resources professional template highlighting recruitment, training, and employee relations experience.',
                'preview_image' => 'cv-templates/hr-specialist-preview.jpg',
                'category' => 'specialized',
                'price' => 320.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 80,
                'features' => ['HR Focus', 'Professional', 'Achievement Based'],
                'layout_type' => 'two-column',
                'color_scheme' => 'orange',
                'file_path' => 'cv.templates.hr-specialist',
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'name' => 'Teacher Educator',
                'slug' => 'teacher-educator',
                'description' => 'Education professional template for teachers and educators. Emphasizes teaching experience and qualifications.',
                'preview_image' => 'cv-templates/teacher-educator-preview.jpg',
                'category' => 'specialized',
                'price' => 300.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 80,
                'features' => ['Education Focus', 'Teaching Experience', 'Professional'],
                'layout_type' => 'single-column',
                'color_scheme' => 'green',
                'file_path' => 'cv.templates.teacher-educator',
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'name' => 'Journalist Writer',
                'slug' => 'journalist-writer',
                'description' => 'Creative template for journalists and writers. Showcases published work and writing portfolio.',
                'preview_image' => 'cv-templates/journalist-writer-preview.jpg',
                'category' => 'specialized',
                'price' => 330.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 80,
                'features' => ['Portfolio Focus', 'Creative', 'Publications'],
                'layout_type' => 'sidebar',
                'color_scheme' => 'red',
                'file_path' => 'cv.templates.journalist-writer',
                'is_active' => true,
                'sort_order' => 25,
            ],
            [
                'name' => 'Consultant Strategy',
                'slug' => 'consultant-strategy',
                'description' => 'Professional consulting template highlighting strategic projects and business impact.',
                'preview_image' => 'cv-templates/consultant-strategy-preview.jpg',
                'category' => 'specialized',
                'price' => 420.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 90,
                'features' => ['Consulting Focus', 'Impact Driven', 'Professional'],
                'layout_type' => 'two-column',
                'color_scheme' => 'navy',
                'file_path' => 'cv.templates.consultant-strategy',
                'is_active' => true,
                'sort_order' => 26,
            ],
            [
                'name' => 'Entrepreneur Startup',
                'slug' => 'entrepreneur-startup',
                'description' => 'Dynamic template for entrepreneurs and startup founders. Highlights ventures, achievements, and innovation.',
                'preview_image' => 'cv-templates/entrepreneur-startup-preview.jpg',
                'category' => 'specialized',
                'price' => 400.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['Entrepreneurial Focus', 'Achievement Based', 'Modern'],
                'layout_type' => 'two-column',
                'color_scheme' => 'orange',
                'file_path' => 'cv.templates.entrepreneur-startup',
                'is_active' => true,
                'sort_order' => 27,
            ],
            [
                'name' => 'Hospitality Manager',
                'slug' => 'hospitality-manager',
                'description' => 'Hospitality industry template for managers and professionals. Emphasizes customer service and operations.',
                'preview_image' => 'cv-templates/hospitality-manager-preview.jpg',
                'category' => 'specialized',
                'price' => 310.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 80,
                'features' => ['Hospitality Focus', 'Service Oriented', 'Professional'],
                'layout_type' => 'two-column',
                'color_scheme' => 'gold',
                'file_path' => 'cv.templates.hospitality-manager',
                'is_active' => true,
                'sort_order' => 28,
            ],
            [
                'name' => 'Retail Manager',
                'slug' => 'retail-manager',
                'description' => 'Retail management template highlighting sales performance and team leadership.',
                'preview_image' => 'cv-templates/retail-manager-preview.jpg',
                'category' => 'specialized',
                'price' => 300.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 75,
                'features' => ['Retail Focus', 'Sales Metrics', 'Team Leadership'],
                'layout_type' => 'two-column',
                'color_scheme' => 'green',
                'file_path' => 'cv.templates.retail-manager',
                'is_active' => true,
                'sort_order' => 29,
            ],
            [
                'name' => 'Logistics Coordinator',
                'slug' => 'logistics-coordinator',
                'description' => 'Supply chain and logistics professional template. Emphasizes operations management and efficiency.',
                'preview_image' => 'cv-templates/logistics-coordinator-preview.jpg',
                'category' => 'specialized',
                'price' => 320.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 80,
                'features' => ['Logistics Focus', 'Operations', 'Efficiency Metrics'],
                'layout_type' => 'two-column',
                'color_scheme' => 'blue',
                'file_path' => 'cv.templates.logistics-coordinator',
                'is_active' => true,
                'sort_order' => 30,
            ],
            // Additional 18 Templates (31-48)
            [
                'name' => 'Business Analyst',
                'slug' => 'business-analyst',
                'description' => 'Analytical template for business analysts focusing on data-driven insights and process improvement.',
                'preview_image' => 'cv-templates/business-analyst-preview.jpg',
                'category' => 'specialized',
                'price' => 340.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['Analytics Focus', 'Process Diagrams', 'Metrics Display', 'Data Driven'],
                'layout_type' => 'two-column',
                'color_scheme' => 'blue',
                'file_path' => 'cv.templates.business-analyst',
                'is_active' => true,
                'sort_order' => 31,
            ],
            [
                'name' => 'Product Manager',
                'slug' => 'product-manager',
                'description' => 'Strategic template for product managers showcasing product roadmaps and launch successes.',
                'preview_image' => 'cv-templates/product-manager-preview.jpg',
                'category' => 'specialized',
                'price' => 380.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['Product Roadmap', 'Launch History', 'KPI Metrics', 'Strategic'],
                'layout_type' => 'modern',
                'color_scheme' => 'purple',
                'file_path' => 'cv.templates.product-manager',
                'is_active' => true,
                'sort_order' => 32,
            ],
            [
                'name' => 'Graphic Designer',
                'slug' => 'graphic-designer',
                'description' => 'Visually stunning template for graphic designers with portfolio showcase.',
                'preview_image' => 'cv-templates/graphic-designer-preview.jpg',
                'category' => 'creative',
                'price' => 360.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 80,
                'features' => ['Visual Portfolio', 'Color Palette', 'Creative Layout', 'Modern'],
                'layout_type' => 'creative',
                'color_scheme' => 'rainbow',
                'file_path' => 'cv.templates.graphic-designer',
                'is_active' => true,
                'sort_order' => 33,
            ],
            [
                'name' => 'UX/UI Designer',
                'slug' => 'ux-designer',
                'description' => 'User-centered design template for UX/UI professionals highlighting design thinking.',
                'preview_image' => 'cv-templates/ux-designer-preview.jpg',
                'category' => 'creative',
                'price' => 380.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['Design Process', 'Tool Proficiency', 'User-Centered', 'Portfolio'],
                'layout_type' => 'modern',
                'color_scheme' => 'blue',
                'file_path' => 'cv.templates.ux-designer',
                'is_active' => true,
                'sort_order' => 34,
            ],
            [
                'name' => 'Sales Executive',
                'slug' => 'sales-executive',
                'description' => 'Results-driven template for sales professionals emphasizing achievements and quotas.',
                'preview_image' => 'cv-templates/sales-executive-preview.jpg',
                'category' => 'corporate',
                'price' => 300.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 75,
                'features' => ['Sales Metrics', 'Achievement Focus', 'Target Display', 'Professional'],
                'layout_type' => 'two-column',
                'color_scheme' => 'green',
                'file_path' => 'cv.templates.sales-executive',
                'is_active' => true,
                'sort_order' => 35,
            ],
            [
                'name' => 'Marketing Manager',
                'slug' => 'marketing-manager',
                'description' => 'Dynamic template for marketing professionals showcasing campaigns and brand strategy.',
                'preview_image' => 'cv-templates/marketing-manager-preview.jpg',
                'category' => 'corporate',
                'price' => 350.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 80,
                'features' => ['Campaign History', 'ROI Metrics', 'Brand Strategy', 'Creative'],
                'layout_type' => 'modern',
                'color_scheme' => 'orange',
                'file_path' => 'cv.templates.marketing-manager',
                'is_active' => true,
                'sort_order' => 36,
            ],
            [
                'name' => 'Software Engineer',
                'slug' => 'software-engineer',
                'description' => 'Technical template for software engineers with GitHub integration and project showcase.',
                'preview_image' => 'cv-templates/software-engineer-preview.jpg',
                'category' => 'specialized',
                'price' => 380.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['GitHub Integration', 'Tech Stack', 'Code Projects', 'Modern'],
                'layout_type' => 'modern',
                'color_scheme' => 'dark',
                'file_path' => 'cv.templates.software-engineer',
                'is_active' => true,
                'sort_order' => 37,
            ],
            [
                'name' => 'DevOps Engineer',
                'slug' => 'devops-engineer',
                'description' => 'Infrastructure-focused template for DevOps professionals showcasing CI/CD pipelines.',
                'preview_image' => 'cv-templates/devops-engineer-preview.jpg',
                'category' => 'specialized',
                'price' => 400.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['CI/CD Pipeline', 'Cloud Platforms', 'Automation', 'Infrastructure'],
                'layout_type' => 'technical',
                'color_scheme' => 'blue',
                'file_path' => 'cv.templates.devops-engineer',
                'is_active' => true,
                'sort_order' => 38,
            ],
            [
                'name' => 'Cybersecurity Specialist',
                'slug' => 'cybersecurity',
                'description' => 'Security-focused template for cybersecurity professionals with threat analysis emphasis.',
                'preview_image' => 'cv-templates/cybersecurity-preview.jpg',
                'category' => 'specialized',
                'price' => 420.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 90,
                'features' => ['Security Certifications', 'Threat Analysis', 'Compliance', 'Technical'],
                'layout_type' => 'technical',
                'color_scheme' => 'red',
                'file_path' => 'cv.templates.cybersecurity',
                'is_active' => true,
                'sort_order' => 39,
            ],
            [
                'name' => 'Cloud Solutions Architect',
                'slug' => 'cloud-architect',
                'description' => 'Enterprise-level template for cloud architects focusing on AWS, Azure, and GCP.',
                'preview_image' => 'cv-templates/cloud-architect-preview.jpg',
                'category' => 'specialized',
                'price' => 450.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 90,
                'features' => ['AWS/Azure/GCP', 'Architecture Diagrams', 'Cloud Migration', 'Enterprise'],
                'layout_type' => 'technical',
                'color_scheme' => 'blue',
                'file_path' => 'cv.templates.cloud-architect',
                'is_active' => true,
                'sort_order' => 40,
            ],
            [
                'name' => 'Machine Learning Engineer',
                'slug' => 'machine-learning',
                'description' => 'AI-focused template for ML engineers showcasing models and research.',
                'preview_image' => 'cv-templates/machine-learning-preview.jpg',
                'category' => 'specialized',
                'price' => 450.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 90,
                'features' => ['AI/ML Models', 'Research Papers', 'Algorithms', 'Innovation'],
                'layout_type' => 'technical',
                'color_scheme' => 'purple',
                'file_path' => 'cv.templates.machine-learning',
                'is_active' => true,
                'sort_order' => 41,
            ],
            [
                'name' => 'Mobile App Developer',
                'slug' => 'mobile-developer',
                'description' => 'Mobile-first template for iOS and Android developers with app portfolio.',
                'preview_image' => 'cv-templates/mobile-developer-preview.jpg',
                'category' => 'specialized',
                'price' => 380.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['iOS/Android', 'App Portfolio', 'Cross-Platform', 'Modern'],
                'layout_type' => 'modern',
                'color_scheme' => 'gradient',
                'file_path' => 'cv.templates.mobile-developer',
                'is_active' => true,
                'sort_order' => 42,
            ],
            [
                'name' => 'Full Stack Developer',
                'slug' => 'fullstack-developer',
                'description' => 'Comprehensive template for full stack developers showcasing frontend and backend skills.',
                'preview_image' => 'cv-templates/fullstack-developer-preview.jpg',
                'category' => 'specialized',
                'price' => 400.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['Frontend/Backend', 'Tech Stack', 'Projects', 'Versatile'],
                'layout_type' => 'modern',
                'color_scheme' => 'dark',
                'file_path' => 'cv.templates.fullstack-developer',
                'is_active' => true,
                'sort_order' => 43,
            ],
            [
                'name' => 'Registered Nurse',
                'slug' => 'nurse',
                'description' => 'Healthcare template for registered nurses emphasizing patient care and clinical skills.',
                'preview_image' => 'cv-templates/nurse-preview.jpg',
                'category' => 'specialized',
                'price' => 300.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 80,
                'features' => ['Clinical Skills', 'Patient Care', 'Certifications', 'Compassionate'],
                'layout_type' => 'professional',
                'color_scheme' => 'blue',
                'file_path' => 'cv.templates.nurse',
                'is_active' => true,
                'sort_order' => 44,
            ],
            [
                'name' => 'Pharmacist Professional',
                'slug' => 'pharmacist',
                'description' => 'Pharmaceutical template for licensed pharmacists with clinical experience focus.',
                'preview_image' => 'cv-templates/pharmacist-preview.jpg',
                'category' => 'specialized',
                'price' => 320.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 85,
                'features' => ['License Display', 'Clinical Experience', 'Certifications', 'Healthcare'],
                'layout_type' => 'professional',
                'color_scheme' => 'green',
                'file_path' => 'cv.templates.pharmacist',
                'is_active' => true,
                'sort_order' => 45,
            ],
            [
                'name' => 'Investment Banker',
                'slug' => 'investment-banker',
                'description' => 'Premium executive template for investment banking professionals.',
                'preview_image' => 'cv-templates/investment-banker-preview.jpg',
                'category' => 'corporate',
                'price' => 500.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 95,
                'features' => ['Deal Experience', 'Financial Modeling', 'M&A', 'Executive'],
                'layout_type' => 'executive',
                'color_scheme' => 'gold',
                'file_path' => 'cv.templates.investment-banker',
                'is_active' => true,
                'sort_order' => 46,
            ],
            [
                'name' => 'Blockchain Developer',
                'slug' => 'blockchain-dev',
                'description' => 'Cutting-edge template for blockchain developers and Web3 professionals.',
                'preview_image' => 'cv-templates/blockchain-dev-preview.jpg',
                'category' => 'specialized',
                'price' => 480.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 90,
                'features' => ['Smart Contracts', 'DApps', 'Cryptocurrency', 'Web3'],
                'layout_type' => 'modern',
                'color_scheme' => 'gradient',
                'file_path' => 'cv.templates.blockchain-dev',
                'is_active' => true,
                'sort_order' => 47,
            ],
            [
                'name' => 'Real Estate Professional',
                'slug' => 'real-estate-agent',
                'description' => 'Property-focused template for real estate agents showcasing sales records.',
                'preview_image' => 'cv-templates/real-estate-agent-preview.jpg',
                'category' => 'specialized',
                'price' => 300.00,
                'can_purchase_with_points' => false,
                'points_required' => null,
                'min_profile_completion' => 75,
                'features' => ['Sales Record', 'Property Portfolio', 'Client Testimonials', 'Professional'],
                'layout_type' => 'professional',
                'color_scheme' => 'brown',
                'file_path' => 'cv.templates.real-estate-agent',
                'is_active' => true,
                'sort_order' => 48,
            ],
        ];

        foreach ($templates as $template) {
            CvTemplate::create($template);
        }

        $freeTemplates = count(array_filter($templates, fn($t) => $t['can_purchase_with_points'] ?? false));
        $paidTemplates = count($templates) - $freeTemplates;

        $this->command->info('✅ Created ' . count($templates) . ' CV templates');
        $this->command->info('🎁 Free with points: ' . $freeTemplates . ' templates');
        $this->command->info('💰 Paid templates: ' . $paidTemplates . ' templates');
        $this->command->info('📊 Price range: ৳200 - ৳500');
    }
}
