<?php

namespace Database\Seeders;

use App\Models\CvTemplate;
use Illuminate\Database\Seeder;

class CvTemplateSeederCompatible extends Seeder
{
    /**
     * Run the database seeds - Compatible version with bideshgomon-api schema.
     */
    public function run(): void
    {
        // Clear existing templates
        CvTemplate::query()->delete();
        
        // Map from bgproject templates to bideshgomon-api schema
        $templates = [
            // FREE
            [
                'name' => 'Basic Starter',
                'slug' => 'basic-clean',
                'description' => 'Completely free CV template for everyone. Simple, clean layout perfect for getting started quickly.',
                'thumbnail' => 'cv-templates/basic-clean-preview.jpg',
                'category' => 'professional',
                'is_premium' => false,
                'price' => 0.00,
                'color_scheme' => ['primary' => '#6b7280', 'secondary' => '#9ca3af', 'accent' => '#4b5563', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills'],
                'is_active' => true,
                'sort_order' => 0,
            ],
            [
                'name' => 'Simple Professional',
                'slug' => 'simple-professional',
                'description' => 'Clean and minimalist CV template perfect for fresh graduates and entry-level professionals. ATS-friendly format.',
                'thumbnail' => 'cv-templates/simple-professional-preview.jpg',
                'category' => 'professional',
                'is_premium' => false,
                'price' => 200.00,
                'color_scheme' => ['primary' => '#000000', 'secondary' => '#333333', 'accent' => '#666666', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills'],
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Minimalist Elite',
                'slug' => 'minimalist-elite',
                'description' => 'Ultra-clean design with maximum readability. Less is more approach for confident professionals.',
                'thumbnail' => 'cv-templates/minimalist-elite-preview.jpg',
                'category' => 'modern',
                'is_premium' => false,
                'price' => 280.00,
                'color_scheme' => ['primary' => '#6b7280', 'secondary' => '#9ca3af', 'accent' => '#4b5563', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills'],
                'is_active' => true,
                'sort_order' => 2,
            ],

            // PAID TEMPLATES
            [
                'name' => 'Modern Professional',
                'slug' => 'modern-professional',
                'description' => 'Contemporary design with professional styling. Perfect for corporate jobs and experienced professionals.',
                'thumbnail' => 'cv-templates/modern-professional-preview.jpg',
                'category' => 'modern',
                'is_premium' => true,
                'price' => 250.00,
                'color_scheme' => ['primary' => '#3b82f6', 'secondary' => '#60a5fa', 'accent' => '#2563eb', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'languages'],
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Creative Designer',
                'slug' => 'creative-designer',
                'description' => 'Bold and colorful template for creative professionals. Stand out from the crowd with unique styling.',
                'thumbnail' => 'cv-templates/creative-designer-preview.jpg',
                'category' => 'creative',
                'is_premium' => true,
                'price' => 300.00,
                'color_scheme' => ['primary' => '#f59e0b', 'secondary' => '#fbbf24', 'accent' => '#d97706', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'portfolio', 'experience', 'education', 'skills'],
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Corporate Executive',
                'slug' => 'corporate-executive',
                'description' => 'Elegant template for senior positions and executives. Professional and sophisticated design.',
                'thumbnail' => 'cv-templates/corporate-executive-preview.jpg',
                'category' => 'executive',
                'is_premium' => true,
                'price' => 350.00,
                'color_scheme' => ['primary' => '#1e40af', 'secondary' => '#3b82f6', 'accent' => '#1e3a8a', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'executive_summary', 'experience', 'education', 'skills', 'certifications'],
                'is_active' => true,
                'sort_order' => 5,
            ],
        ];

        // Add 42 more specialized templates
        $additionalTemplates = $this->getAdditionalTemplates();
        $templates = array_merge($templates, $additionalTemplates);

        foreach ($templates as $template) {
            CvTemplate::create($template);
        }

        $this->command->info('✅ Created ' . count($templates) . ' CV templates successfully!');
    }

    private function getAdditionalTemplates(): array
    {
        return [
            // Templates 7-48
            [
                'name' => 'IT Developer Pro',
                'slug' => 'it-developer-pro',
                'description' => 'Tech-focused CV template highlighting skills and projects. Perfect for software developers and IT professionals.',
                'thumbnail' => 'cv-templates/it-developer-pro-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 300.00,
                'color_scheme' => ['primary' => '#10b981', 'secondary' => '#34d399', 'accent' => '#059669', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'technical_skills', 'experience', 'projects', 'education'],
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Healthcare Professional',
                'slug' => 'healthcare-professional',
                'description' => 'Specialized template for doctors, nurses, and healthcare workers. Emphasizes certifications and experience.',
                'thumbnail' => 'cv-templates/healthcare-professional-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 350.00,
                'color_scheme' => ['primary' => '#14b8a6', 'secondary' => '#5eead4', 'accent' => '#0d9488', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'certifications', 'skills'],
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'International Format',
                'slug' => 'international-format',
                'description' => 'Global standard CV format for international job applications. Compatible with worldwide ATS systems.',
                'thumbnail' => 'cv-templates/international-format-preview.jpg',
                'category' => 'ats-friendly',
                'is_premium' => true,
                'price' => 400.00,
                'color_scheme' => ['primary' => '#000000', 'secondary' => '#333333', 'accent' => '#666666', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'languages'],
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Premium Executive',
                'slug' => 'premium-executive',
                'description' => 'Top-tier template for C-level executives and senior management. Sophisticated and commanding presence.',
                'thumbnail' => 'cv-templates/premium-executive-preview.jpg',
                'category' => 'executive',
                'is_premium' => true,
                'price' => 500.00,
                'color_scheme' => ['primary' => '#d97706', 'secondary' => '#f59e0b', 'accent' => '#b45309', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'executive_summary', 'experience', 'education', 'skills', 'certifications', 'awards'],
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Elegant Two Column',
                'slug' => 'elegant-two-column',
                'description' => 'Sophisticated two-column layout with gradient sidebar. Perfect for professionals seeking an elegant presentation.',
                'thumbnail' => 'cv-templates/elegant-two-column-preview.jpg',
                'category' => 'modern',
                'is_premium' => true,
                'price' => 320.00,
                'color_scheme' => ['primary' => '#9333ea', 'secondary' => '#a855f7', 'accent' => '#7e22ce', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'languages'],
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Vibrant Modern',
                'slug' => 'vibrant-modern',
                'description' => 'Eye-catching colorful design with gradient accents. Stand out with a bold, modern presentation.',
                'thumbnail' => 'cv-templates/vibrant-modern-preview.jpg',
                'category' => 'creative',
                'is_premium' => true,
                'price' => 350.00,
                'color_scheme' => ['primary' => '#f97316', 'secondary' => '#fb923c', 'accent' => '#ea580c', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills'],
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Academic Research',
                'slug' => 'academic-research',
                'description' => 'Formal template designed for academics, researchers, and scholars. Emphasizes publications and research output.',
                'thumbnail' => 'cv-templates/academic-research-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 380.00,
                'color_scheme' => ['primary' => '#000000', 'secondary' => '#333333', 'accent' => '#666666', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'education', 'experience', 'publications', 'skills'],
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Sales & Marketing',
                'slug' => 'sales-marketing',
                'description' => 'Dynamic template for sales and marketing professionals. Highlights achievements and metrics with visual impact.',
                'thumbnail' => 'cv-templates/sales-marketing-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 340.00,
                'color_scheme' => ['primary' => '#ef4444', 'secondary' => '#f87171', 'accent' => '#dc2626', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'achievements'],
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Designer Portfolio',
                'slug' => 'designer-portfolio',
                'description' => 'Creative portfolio-style CV for designers and creatives. Showcases work with a modern, minimalist aesthetic.',
                'thumbnail' => 'cv-templates/designer-portfolio-preview.jpg',
                'category' => 'creative',
                'is_premium' => true,
                'price' => 420.00,
                'color_scheme' => ['primary' => '#000000', 'secondary' => '#333333', 'accent' => '#666666', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'portfolio', 'experience', 'education', 'skills'],
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Tech Specialist',
                'slug' => 'tech-specialist',
                'description' => 'Technology specialist template with modern design. Perfect for IT professionals and technical roles.',
                'thumbnail' => 'cv-templates/tech-specialist-preview.jpg',
                'category' => 'modern',
                'is_premium' => true,
                'price' => 320.00,
                'color_scheme' => ['primary' => '#3b82f6', 'secondary' => '#60a5fa', 'accent' => '#2563eb', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'technical_skills', 'experience', 'projects', 'education'],
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Finance Executive',
                'slug' => 'finance-executive',
                'description' => 'Professional template for finance professionals and executives. Emphasizes analytical skills and achievements.',
                'thumbnail' => 'cv-templates/finance-executive-preview.jpg',
                'category' => 'executive',
                'is_premium' => true,
                'price' => 420.00,
                'color_scheme' => ['primary' => '#1e40af', 'secondary' => '#3b82f6', 'accent' => '#1e3a8a', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'executive_summary', 'experience', 'education', 'skills', 'certifications'],
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Medical Professional',
                'slug' => 'medical-professional',
                'description' => 'Comprehensive medical CV template for doctors and medical practitioners. Highlights qualifications and experience.',
                'thumbnail' => 'cv-templates/medical-professional-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 380.00,
                'color_scheme' => ['primary' => '#14b8a6', 'secondary' => '#5eead4', 'accent' => '#0d9488', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'certifications', 'skills'],
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Legal Counsel',
                'slug' => 'legal-counsel',
                'description' => 'Professional template for lawyers and legal professionals. Emphasizes education, cases, and bar admissions.',
                'thumbnail' => 'cv-templates/legal-counsel-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 400.00,
                'color_scheme' => ['primary' => '#1e40af', 'secondary' => '#3b82f6', 'accent' => '#1e3a8a', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'bar_admissions', 'skills'],
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'name' => 'Engineer Technical',
                'slug' => 'engineer-technical',
                'description' => 'Engineering-focused CV template highlighting technical skills and projects. Perfect for engineers and technical professionals.',
                'thumbnail' => 'cv-templates/engineer-technical-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 340.00,
                'color_scheme' => ['primary' => '#3b82f6', 'secondary' => '#60a5fa', 'accent' => '#2563eb', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'technical_skills', 'experience', 'projects', 'education'],
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'name' => 'Architect Planner',
                'slug' => 'architect-planner',
                'description' => 'Specialized template for architects and urban planners. Showcases projects and design philosophy.',
                'thumbnail' => 'cv-templates/architect-planner-preview.jpg',
                'category' => 'creative',
                'is_premium' => true,
                'price' => 360.00,
                'color_scheme' => ['primary' => '#6b7280', 'secondary' => '#9ca3af', 'accent' => '#4b5563', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'projects', 'experience', 'education', 'skills'],
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'name' => 'Data Scientist',
                'slug' => 'data-scientist',
                'description' => 'Data science professional template emphasizing technical skills, projects, and analytical capabilities.',
                'thumbnail' => 'cv-templates/data-scientist-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 380.00,
                'color_scheme' => ['primary' => '#9333ea', 'secondary' => '#a855f7', 'accent' => '#7e22ce', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'technical_skills', 'experience', 'projects', 'education'],
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'name' => 'HR Specialist',
                'slug' => 'hr-specialist',
                'description' => 'Human resources professional template highlighting recruitment, training, and employee relations experience.',
                'thumbnail' => 'cv-templates/hr-specialist-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 320.00,
                'color_scheme' => ['primary' => '#f97316', 'secondary' => '#fb923c', 'accent' => '#ea580c', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'certifications'],
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'name' => 'Teacher Educator',
                'slug' => 'teacher-educator',
                'description' => 'Education professional template for teachers and educators. Emphasizes teaching experience and qualifications.',
                'thumbnail' => 'cv-templates/teacher-educator-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 300.00,
                'color_scheme' => ['primary' => '#10b981', 'secondary' => '#34d399', 'accent' => '#059669', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'certifications'],
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'name' => 'Journalist Writer',
                'slug' => 'journalist-writer',
                'description' => 'Creative template for journalists and writers. Showcases published work and writing portfolio.',
                'thumbnail' => 'cv-templates/journalist-writer-preview.jpg',
                'category' => 'creative',
                'is_premium' => true,
                'price' => 330.00,
                'color_scheme' => ['primary' => '#ef4444', 'secondary' => '#f87171', 'accent' => '#dc2626', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'publications', 'experience', 'education', 'skills'],
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'name' => 'Consultant Strategy',
                'slug' => 'consultant-strategy',
                'description' => 'Professional consulting template highlighting strategic projects and business impact.',
                'thumbnail' => 'cv-templates/consultant-strategy-preview.jpg',
                'category' => 'executive',
                'is_premium' => true,
                'price' => 420.00,
                'color_scheme' => ['primary' => '#1e40af', 'secondary' => '#3b82f6', 'accent' => '#1e3a8a', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'executive_summary', 'experience', 'education', 'skills', 'achievements'],
                'is_active' => true,
                'sort_order' => 25,
            ],
            [
                'name' => 'Entrepreneur Startup',
                'slug' => 'entrepreneur-startup',
                'description' => 'Dynamic template for entrepreneurs and startup founders. Highlights ventures, achievements, and innovation.',
                'thumbnail' => 'cv-templates/entrepreneur-startup-preview.jpg',
                'category' => 'modern',
                'is_premium' => true,
                'price' => 400.00,
                'color_scheme' => ['primary' => '#f97316', 'secondary' => '#fb923c', 'accent' => '#ea580c', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'ventures', 'experience', 'education', 'skills'],
                'is_active' => true,
                'sort_order' => 26,
            ],
            [
                'name' => 'Hospitality Manager',
                'slug' => 'hospitality-manager',
                'description' => 'Hospitality industry template for managers and professionals. Emphasizes customer service and operations.',
                'thumbnail' => 'cv-templates/hospitality-manager-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 310.00,
                'color_scheme' => ['primary' => '#d97706', 'secondary' => '#f59e0b', 'accent' => '#b45309', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'certifications'],
                'is_active' => true,
                'sort_order' => 27,
            ],
            [
                'name' => 'Retail Manager',
                'slug' => 'retail-manager',
                'description' => 'Retail management template highlighting sales performance and team leadership.',
                'thumbnail' => 'cv-templates/retail-manager-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 300.00,
                'color_scheme' => ['primary' => '#10b981', 'secondary' => '#34d399', 'accent' => '#059669', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'achievements'],
                'is_active' => true,
                'sort_order' => 28,
            ],
            [
                'name' => 'Logistics Coordinator',
                'slug' => 'logistics-coordinator',
                'description' => 'Supply chain and logistics professional template. Emphasizes operations management and efficiency.',
                'thumbnail' => 'cv-templates/logistics-coordinator-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 320.00,
                'color_scheme' => ['primary' => '#3b82f6', 'secondary' => '#60a5fa', 'accent' => '#2563eb', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'certifications'],
                'is_active' => true,
                'sort_order' => 29,
            ],
            [
                'name' => 'Business Analyst',
                'slug' => 'business-analyst',
                'description' => 'Analytical template for business analysts focusing on data-driven insights and process improvement.',
                'thumbnail' => 'cv-templates/business-analyst-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 340.00,
                'color_scheme' => ['primary' => '#3b82f6', 'secondary' => '#60a5fa', 'accent' => '#2563eb', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'technical_skills', 'experience', 'education', 'certifications'],
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'name' => 'Product Manager',
                'slug' => 'product-manager',
                'description' => 'Strategic template for product managers showcasing product roadmaps and launch successes.',
                'thumbnail' => 'cv-templates/product-manager-preview.jpg',
                'category' => 'modern',
                'is_premium' => true,
                'price' => 380.00,
                'color_scheme' => ['primary' => '#9333ea', 'secondary' => '#a855f7', 'accent' => '#7e22ce', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'achievements'],
                'is_active' => true,
                'sort_order' => 31,
            ],
            [
                'name' => 'Graphic Designer',
                'slug' => 'graphic-designer',
                'description' => 'Visually stunning template for graphic designers with portfolio showcase.',
                'thumbnail' => 'cv-templates/graphic-designer-preview.jpg',
                'category' => 'creative',
                'is_premium' => true,
                'price' => 360.00,
                'color_scheme' => ['primary' => '#ec4899', 'secondary' => '#f472b6', 'accent' => '#db2777', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'portfolio', 'experience', 'education', 'skills'],
                'is_active' => true,
                'sort_order' => 32,
            ],
            [
                'name' => 'UX/UI Designer',
                'slug' => 'ux-designer',
                'description' => 'User-centered design template for UX/UI professionals highlighting design thinking.',
                'thumbnail' => 'cv-templates/ux-designer-preview.jpg',
                'category' => 'creative',
                'is_premium' => true,
                'price' => 380.00,
                'color_scheme' => ['primary' => '#3b82f6', 'secondary' => '#60a5fa', 'accent' => '#2563eb', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'portfolio', 'experience', 'education', 'skills'],
                'is_active' => true,
                'sort_order' => 33,
            ],
            [
                'name' => 'Sales Executive',
                'slug' => 'sales-executive',
                'description' => 'Results-driven template for sales professionals emphasizing achievements and quotas.',
                'thumbnail' => 'cv-templates/sales-executive-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 300.00,
                'color_scheme' => ['primary' => '#10b981', 'secondary' => '#34d399', 'accent' => '#059669', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'achievements'],
                'is_active' => true,
                'sort_order' => 34,
            ],
            [
                'name' => 'Marketing Manager',
                'slug' => 'marketing-manager',
                'description' => 'Dynamic template for marketing professionals showcasing campaigns and brand strategy.',
                'thumbnail' => 'cv-templates/marketing-manager-preview.jpg',
                'category' => 'modern',
                'is_premium' => true,
                'price' => 350.00,
                'color_scheme' => ['primary' => '#f97316', 'secondary' => '#fb923c', 'accent' => '#ea580c', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'campaigns'],
                'is_active' => true,
                'sort_order' => 35,
            ],
            [
                'name' => 'Software Engineer',
                'slug' => 'software-engineer',
                'description' => 'Technical template for software engineers with GitHub integration and project showcase.',
                'thumbnail' => 'cv-templates/software-engineer-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 380.00,
                'color_scheme' => ['primary' => '#1f2937', 'secondary' => '#374151', 'accent' => '#111827', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'technical_skills', 'experience', 'projects', 'education'],
                'is_active' => true,
                'sort_order' => 36,
            ],
            [
                'name' => 'DevOps Engineer',
                'slug' => 'devops-engineer',
                'description' => 'Infrastructure-focused template for DevOps professionals showcasing CI/CD pipelines.',
                'thumbnail' => 'cv-templates/devops-engineer-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 400.00,
                'color_scheme' => ['primary' => '#3b82f6', 'secondary' => '#60a5fa', 'accent' => '#2563eb', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'technical_skills', 'experience', 'projects', 'education'],
                'is_active' => true,
                'sort_order' => 37,
            ],
            [
                'name' => 'Cybersecurity Specialist',
                'slug' => 'cybersecurity',
                'description' => 'Security-focused template for cybersecurity professionals with threat analysis emphasis.',
                'thumbnail' => 'cv-templates/cybersecurity-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 420.00,
                'color_scheme' => ['primary' => '#ef4444', 'secondary' => '#f87171', 'accent' => '#dc2626', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'technical_skills', 'experience', 'certifications', 'education'],
                'is_active' => true,
                'sort_order' => 38,
            ],
            [
                'name' => 'Cloud Solutions Architect',
                'slug' => 'cloud-architect',
                'description' => 'Enterprise-level template for cloud architects focusing on AWS, Azure, and GCP.',
                'thumbnail' => 'cv-templates/cloud-architect-preview.jpg',
                'category' => 'executive',
                'is_premium' => true,
                'price' => 450.00,
                'color_scheme' => ['primary' => '#3b82f6', 'secondary' => '#60a5fa', 'accent' => '#2563eb', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'executive_summary', 'technical_skills', 'experience', 'certifications', 'education'],
                'is_active' => true,
                'sort_order' => 39,
            ],
            [
                'name' => 'Machine Learning Engineer',
                'slug' => 'machine-learning',
                'description' => 'AI-focused template for ML engineers showcasing models and research.',
                'thumbnail' => 'cv-templates/machine-learning-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 450.00,
                'color_scheme' => ['primary' => '#9333ea', 'secondary' => '#a855f7', 'accent' => '#7e22ce', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'technical_skills', 'experience', 'projects', 'education'],
                'is_active' => true,
                'sort_order' => 40,
            ],
            [
                'name' => 'Mobile App Developer',
                'slug' => 'mobile-developer',
                'description' => 'Mobile-first template for iOS and Android developers with app portfolio.',
                'thumbnail' => 'cv-templates/mobile-developer-preview.jpg',
                'category' => 'modern',
                'is_premium' => true,
                'price' => 380.00,
                'color_scheme' => ['primary' => '#06b6d4', 'secondary' => '#22d3ee', 'accent' => '#0891b2', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'technical_skills', 'experience', 'projects', 'education'],
                'is_active' => true,
                'sort_order' => 41,
            ],
            [
                'name' => 'Full Stack Developer',
                'slug' => 'fullstack-developer',
                'description' => 'Comprehensive template for full stack developers showcasing frontend and backend skills.',
                'thumbnail' => 'cv-templates/fullstack-developer-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 400.00,
                'color_scheme' => ['primary' => '#1f2937', 'secondary' => '#374151', 'accent' => '#111827', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'technical_skills', 'experience', 'projects', 'education'],
                'is_active' => true,
                'sort_order' => 42,
            ],
            [
                'name' => 'Registered Nurse',
                'slug' => 'nurse',
                'description' => 'Healthcare template for registered nurses emphasizing patient care and clinical skills.',
                'thumbnail' => 'cv-templates/nurse-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 300.00,
                'color_scheme' => ['primary' => '#3b82f6', 'secondary' => '#60a5fa', 'accent' => '#2563eb', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'certifications', 'skills'],
                'is_active' => true,
                'sort_order' => 43,
            ],
            [
                'name' => 'Pharmacist Professional',
                'slug' => 'pharmacist',
                'description' => 'Pharmaceutical template for licensed pharmacists with clinical experience focus.',
                'thumbnail' => 'cv-templates/pharmacist-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 320.00,
                'color_scheme' => ['primary' => '#10b981', 'secondary' => '#34d399', 'accent' => '#059669', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'certifications', 'skills'],
                'is_active' => true,
                'sort_order' => 44,
            ],
            [
                'name' => 'Investment Banker',
                'slug' => 'investment-banker',
                'description' => 'Premium executive template for investment banking professionals.',
                'thumbnail' => 'cv-templates/investment-banker-preview.jpg',
                'category' => 'executive',
                'is_premium' => true,
                'price' => 500.00,
                'color_scheme' => ['primary' => '#d97706', 'secondary' => '#f59e0b', 'accent' => '#b45309', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'executive_summary', 'experience', 'education', 'skills', 'deals'],
                'is_active' => true,
                'sort_order' => 45,
            ],
            [
                'name' => 'Blockchain Developer',
                'slug' => 'blockchain-dev',
                'description' => 'Cutting-edge template for blockchain developers and Web3 professionals.',
                'thumbnail' => 'cv-templates/blockchain-dev-preview.jpg',
                'category' => 'modern',
                'is_premium' => true,
                'price' => 480.00,
                'color_scheme' => ['primary' => '#06b6d4', 'secondary' => '#22d3ee', 'accent' => '#0891b2', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'technical_skills', 'experience', 'projects', 'education'],
                'is_active' => true,
                'sort_order' => 46,
            ],
            [
                'name' => 'Real Estate Professional',
                'slug' => 'real-estate-agent',
                'description' => 'Property-focused template for real estate agents showcasing sales records.',
                'thumbnail' => 'cv-templates/real-estate-agent-preview.jpg',
                'category' => 'professional',
                'is_premium' => true,
                'price' => 300.00,
                'color_scheme' => ['primary' => '#92400e', 'secondary' => '#b45309', 'accent' => '#78350f', 'text' => '#1f2937'],
                'sections' => ['personal_info', 'summary', 'experience', 'education', 'skills', 'achievements'],
                'is_active' => true,
                'sort_order' => 47,
            ],
        ];
    }
}
