<?php

namespace Database\Seeders;

use App\Models\FlightRoute;
use App\Models\Country;
use App\Models\Currency;
use Illuminate\Database\Seeder;

class FlightRouteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bangladeshId = Country::where('iso_code_2', 'BD')->first()->id;
        $bdtCurrencyId = Currency::where('code', 'BDT')->first()->id;

        $routes = [
            // MIDDLE EAST - Popular worker destinations
            [
                'route_code' => 'DAC-DXB-001',
                'airline_name' => 'Emirates',
                'airline_code' => 'EK',
                'flight_number' => 'EK585',
                'aircraft_type' => 'Boeing 777-300ER',
                'origin_country_id' => $bangladeshId,
                'origin_city' => 'Dhaka',
                'origin_airport' => 'Hazrat Shahjalal International Airport',
                'origin_airport_code' => 'DAC',
                'destination_country_id' => Country::where('iso_code_2', 'AE')->first()->id,
                'destination_city' => 'Dubai',
                'destination_airport' => 'Dubai International Airport',
                'destination_airport_code' => 'DXB',
                'departure_time' => '02:30:00',
                'arrival_time' => '05:30:00',
                'flight_duration' => '5h 00m',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
                'is_direct' => true,
                'stops' => 0,
                'economy_price' => 32000,
                'business_price' => 95000,
                'first_class_price' => 180000,
                'currency_id' => $bdtCurrencyId,
                'total_seats' => 354,
                'economy_seats' => 304,
                'business_seats' => 42,
                'first_class_seats' => 8,
                'cabin_baggage' => '7kg',
                'checked_baggage' => '30kg',
                'extra_baggage_price' => '৳2500 per 5kg',
                'amenities' => ['in-flight-meal', 'wifi', 'entertainment', 'power-outlet', 'blanket'],
                'meal_type' => 'Complimentary',
                'has_wifi' => true,
                'has_entertainment' => true,
                'booking_fee' => 500,
                'cancellation_fee_percentage' => 20,
                'is_popular' => true,
                'display_order' => 1,
                'description' => 'Direct daily flights to Dubai with premium Emirates service. Perfect for UAE workers and business travelers.',
                'tags' => ['worker-friendly', 'direct-flight', 'premium'],
            ],
            [
                'route_code' => 'DAC-RUH-001',
                'airline_name' => 'Saudia',
                'airline_code' => 'SV',
                'flight_number' => 'SV803',
                'aircraft_type' => 'Boeing 777-200',
                'origin_country_id' => $bangladeshId,
                'origin_city' => 'Dhaka',
                'origin_airport' => 'Hazrat Shahjalal International Airport',
                'origin_airport_code' => 'DAC',
                'destination_country_id' => Country::where('iso_code_2', 'SA')->first()->id,
                'destination_city' => 'Riyadh',
                'destination_airport' => 'King Khalid International Airport',
                'destination_airport_code' => 'RUH',
                'departure_time' => '22:00:00',
                'arrival_time' => '02:00:00',
                'flight_duration' => '5h 30m',
                'available_days' => ['sunday', 'tuesday', 'thursday', 'saturday'],
                'is_direct' => true,
                'stops' => 0,
                'economy_price' => 28000,
                'business_price' => 85000,
                'currency_id' => $bdtCurrencyId,
                'total_seats' => 305,
                'economy_seats' => 265,
                'business_seats' => 40,
                'cabin_baggage' => '7kg',
                'checked_baggage' => '30kg',
                'extra_baggage_price' => '৳2000 per 5kg',
                'amenities' => ['in-flight-meal', 'entertainment', 'blanket'],
                'meal_type' => 'Complimentary Halal',
                'has_wifi' => false,
                'has_entertainment' => true,
                'booking_fee' => 500,
                'cancellation_fee_percentage' => 25,
                'is_popular' => true,
                'display_order' => 2,
                'description' => 'Direct flights to Riyadh, Saudi Arabia. Ideal for Hajj, Umrah, and workers in KSA.',
                'tags' => ['worker-friendly', 'hajj-umrah', 'direct-flight'],
            ],
            [
                'route_code' => 'DAC-JED-001',
                'airline_name' => 'Biman Bangladesh Airlines',
                'airline_code' => 'BG',
                'flight_number' => 'BG021',
                'aircraft_type' => 'Boeing 787-8 Dreamliner',
                'origin_country_id' => $bangladeshId,
                'origin_city' => 'Dhaka',
                'origin_airport' => 'Hazrat Shahjalal International Airport',
                'origin_airport_code' => 'DAC',
                'destination_country_id' => Country::where('iso_code_2', 'SA')->first()->id,
                'destination_city' => 'Jeddah',
                'destination_airport' => 'King Abdulaziz International Airport',
                'destination_airport_code' => 'JED',
                'departure_time' => '23:30:00',
                'arrival_time' => '04:30:00',
                'flight_duration' => '6h 00m',
                'available_days' => ['monday', 'wednesday', 'friday', 'sunday'],
                'is_direct' => true,
                'stops' => 0,
                'economy_price' => 26000,
                'business_price' => 78000,
                'currency_id' => $bdtCurrencyId,
                'total_seats' => 271,
                'economy_seats' => 235,
                'business_seats' => 36,
                'cabin_baggage' => '7kg',
                'checked_baggage' => '30kg',
                'extra_baggage_price' => '৳1800 per 5kg',
                'amenities' => ['in-flight-meal', 'entertainment', 'blanket'],
                'meal_type' => 'Complimentary Halal',
                'has_wifi' => false,
                'has_entertainment' => true,
                'booking_fee' => 400,
                'cancellation_fee_percentage' => 20,
                'is_popular' => true,
                'display_order' => 3,
                'description' => 'National carrier direct flights to Jeddah. Special packages for Hajj and Umrah pilgrims.',
                'tags' => ['worker-friendly', 'hajj-umrah', 'budget', 'national-carrier'],
            ],
            [
                'route_code' => 'DAC-DOH-001',
                'airline_name' => 'Qatar Airways',
                'airline_code' => 'QR',
                'flight_number' => 'QR639',
                'aircraft_type' => 'Airbus A350-900',
                'origin_country_id' => $bangladeshId,
                'origin_city' => 'Dhaka',
                'origin_airport' => 'Hazrat Shahjalal International Airport',
                'origin_airport_code' => 'DAC',
                'destination_country_id' => Country::where('iso_code_2', 'QA')->first()->id,
                'destination_city' => 'Doha',
                'destination_airport' => 'Hamad International Airport',
                'destination_airport_code' => 'DOH',
                'departure_time' => '03:00:00',
                'arrival_time' => '05:50:00',
                'flight_duration' => '5h 20m',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
                'is_direct' => true,
                'stops' => 0,
                'economy_price' => 33000,
                'business_price' => 105000,
                'first_class_price' => 200000,
                'currency_id' => $bdtCurrencyId,
                'total_seats' => 283,
                'economy_seats' => 247,
                'business_seats' => 36,
                'cabin_baggage' => '7kg',
                'checked_baggage' => '30kg',
                'extra_baggage_price' => '৳2800 per 5kg',
                'amenities' => ['in-flight-meal', 'wifi', 'entertainment', 'power-outlet', 'comfort-kit'],
                'meal_type' => 'Complimentary Premium',
                'has_wifi' => true,
                'has_entertainment' => true,
                'booking_fee' => 500,
                'cancellation_fee_percentage' => 20,
                'is_popular' => true,
                'display_order' => 4,
                'description' => '5-star airline service to Qatar. Daily flights with award-winning service and comfort.',
                'tags' => ['worker-friendly', 'premium', 'direct-flight'],
            ],

            // SOUTHEAST ASIA
            [
                'route_code' => 'DAC-KUL-001',
                'airline_name' => 'Malaysia Airlines',
                'airline_code' => 'MH',
                'flight_number' => 'MH197',
                'aircraft_type' => 'Airbus A330-300',
                'origin_country_id' => $bangladeshId,
                'origin_city' => 'Dhaka',
                'origin_airport' => 'Hazrat Shahjalal International Airport',
                'origin_airport_code' => 'DAC',
                'destination_country_id' => Country::where('iso_code_2', 'MY')->first()->id,
                'destination_city' => 'Kuala Lumpur',
                'destination_airport' => 'Kuala Lumpur International Airport',
                'destination_airport_code' => 'KUL',
                'departure_time' => '08:00:00',
                'arrival_time' => '14:30:00',
                'flight_duration' => '3h 30m',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
                'is_direct' => true,
                'stops' => 0,
                'economy_price' => 22000,
                'business_price' => 65000,
                'currency_id' => $bdtCurrencyId,
                'total_seats' => 290,
                'economy_seats' => 254,
                'business_seats' => 36,
                'cabin_baggage' => '7kg',
                'checked_baggage' => '30kg',
                'extra_baggage_price' => '৳1500 per 5kg',
                'amenities' => ['in-flight-meal', 'entertainment', 'blanket'],
                'meal_type' => 'Complimentary',
                'has_wifi' => false,
                'has_entertainment' => true,
                'booking_fee' => 400,
                'cancellation_fee_percentage' => 15,
                'is_popular' => true,
                'display_order' => 5,
                'description' => 'Daily flights to Malaysia. Popular for factory workers and students.',
                'tags' => ['worker-friendly', 'budget', 'direct-flight'],
            ],
            [
                'route_code' => 'DAC-SIN-001',
                'airline_name' => 'Singapore Airlines',
                'airline_code' => 'SQ',
                'flight_number' => 'SQ447',
                'aircraft_type' => 'Boeing 737-800',
                'origin_country_id' => $bangladeshId,
                'origin_city' => 'Dhaka',
                'origin_airport' => 'Hazrat Shahjalal International Airport',
                'origin_airport_code' => 'DAC',
                'destination_country_id' => Country::where('iso_code_2', 'SG')->first()->id,
                'destination_city' => 'Singapore',
                'destination_airport' => 'Singapore Changi Airport',
                'destination_airport_code' => 'SIN',
                'departure_time' => '10:30:00',
                'arrival_time' => '17:45:00',
                'flight_duration' => '4h 15m',
                'available_days' => ['tuesday', 'thursday', 'saturday'],
                'is_direct' => true,
                'stops' => 0,
                'economy_price' => 35000,
                'business_price' => 98000,
                'currency_id' => $bdtCurrencyId,
                'total_seats' => 162,
                'economy_seats' => 138,
                'business_seats' => 24,
                'cabin_baggage' => '7kg',
                'checked_baggage' => '30kg',
                'extra_baggage_price' => '৳3000 per 5kg',
                'amenities' => ['in-flight-meal', 'entertainment', 'wifi', 'comfort-kit'],
                'meal_type' => 'Complimentary Premium',
                'has_wifi' => true,
                'has_entertainment' => true,
                'booking_fee' => 600,
                'cancellation_fee_percentage' => 20,
                'is_popular' => false,
                'display_order' => 6,
                'description' => 'Premium service to Singapore. Perfect for business and skilled workers.',
                'tags' => ['premium', 'direct-flight'],
            ],
            [
                'route_code' => 'DAC-BKK-001',
                'airline_name' => 'Thai Airways',
                'airline_code' => 'TG',
                'flight_number' => 'TG321',
                'aircraft_type' => 'Boeing 777-200',
                'origin_country_id' => $bangladeshId,
                'origin_city' => 'Dhaka',
                'origin_airport' => 'Hazrat Shahjalal International Airport',
                'origin_airport_code' => 'DAC',
                'destination_country_id' => Country::where('iso_code_2', 'TH')->first()->id,
                'destination_city' => 'Bangkok',
                'destination_airport' => 'Suvarnabhumi Airport',
                'destination_airport_code' => 'BKK',
                'departure_time' => '09:15:00',
                'arrival_time' => '14:30:00',
                'flight_duration' => '2h 15m',
                'available_days' => ['monday', 'wednesday', 'friday', 'sunday'],
                'is_direct' => true,
                'stops' => 0,
                'economy_price' => 18000,
                'business_price' => 55000,
                'currency_id' => $bdtCurrencyId,
                'total_seats' => 298,
                'economy_seats' => 262,
                'business_seats' => 36,
                'cabin_baggage' => '7kg',
                'checked_baggage' => '30kg',
                'extra_baggage_price' => '৳1200 per 5kg',
                'amenities' => ['in-flight-meal', 'entertainment', 'blanket'],
                'meal_type' => 'Complimentary',
                'has_wifi' => false,
                'has_entertainment' => true,
                'booking_fee' => 300,
                'cancellation_fee_percentage' => 15,
                'is_popular' => true,
                'display_order' => 7,
                'description' => 'Short direct flights to Bangkok. Great for connecting flights and tourism.',
                'tags' => ['budget', 'direct-flight', 'tourism'],
            ],

            // SOUTH ASIA
            [
                'route_code' => 'DAC-DEL-001',
                'airline_name' => 'IndiGo',
                'airline_code' => '6E',
                'flight_number' => '6E091',
                'aircraft_type' => 'Airbus A320neo',
                'origin_country_id' => $bangladeshId,
                'origin_city' => 'Dhaka',
                'origin_airport' => 'Hazrat Shahjalal International Airport',
                'origin_airport_code' => 'DAC',
                'destination_country_id' => Country::where('iso_code_2', 'IN')->first()->id,
                'destination_city' => 'New Delhi',
                'destination_airport' => 'Indira Gandhi International Airport',
                'destination_airport_code' => 'DEL',
                'departure_time' => '06:30:00',
                'arrival_time' => '08:45:00',
                'flight_duration' => '1h 45m',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
                'is_direct' => true,
                'stops' => 0,
                'economy_price' => 12000,
                'currency_id' => $bdtCurrencyId,
                'total_seats' => 180,
                'economy_seats' => 180,
                'cabin_baggage' => '7kg',
                'checked_baggage' => '15kg',
                'extra_baggage_price' => '৳800 per 5kg',
                'amenities' => ['buy-on-board'],
                'meal_type' => 'Buy on Board',
                'has_wifi' => false,
                'has_entertainment' => false,
                'booking_fee' => 200,
                'cancellation_fee_percentage' => 10,
                'is_popular' => false,
                'display_order' => 8,
                'description' => 'Budget flights to Delhi. Daily service with low fares.',
                'tags' => ['budget', 'direct-flight'],
            ],

            // More CGP routes (Chittagong)
            [
                'route_code' => 'CGP-DXB-001',
                'airline_name' => 'Fly Dubai',
                'airline_code' => 'FZ',
                'flight_number' => 'FZ573',
                'aircraft_type' => 'Boeing 737-800',
                'origin_country_id' => $bangladeshId,
                'origin_city' => 'Chittagong',
                'origin_airport' => 'Shah Amanat International Airport',
                'origin_airport_code' => 'CGP',
                'destination_country_id' => Country::where('iso_code_2', 'AE')->first()->id,
                'destination_city' => 'Dubai',
                'destination_airport' => 'Dubai International Airport',
                'destination_airport_code' => 'DXB',
                'departure_time' => '01:45:00',
                'arrival_time' => '05:00:00',
                'flight_duration' => '5h 15m',
                'available_days' => ['monday', 'wednesday', 'friday', 'sunday'],
                'is_direct' => true,
                'stops' => 0,
                'economy_price' => 28000,
                'business_price' => 75000,
                'currency_id' => $bdtCurrencyId,
                'total_seats' => 162,
                'economy_seats' => 150,
                'business_seats' => 12,
                'cabin_baggage' => '7kg',
                'checked_baggage' => '30kg',
                'extra_baggage_price' => '৳2200 per 5kg',
                'amenities' => ['in-flight-meal', 'entertainment'],
                'meal_type' => 'Buy on Board',
                'has_wifi' => false,
                'has_entertainment' => true,
                'booking_fee' => 400,
                'cancellation_fee_percentage' => 20,
                'is_popular' => true,
                'display_order' => 9,
                'description' => 'Direct flights from Chittagong to Dubai. Convenient for Chittagong residents.',
                'tags' => ['worker-friendly', 'direct-flight'],
            ],
            [
                'route_code' => 'CGP-KUL-001',
                'airline_name' => 'AirAsia',
                'airline_code' => 'AK',
                'flight_number' => 'AK081',
                'aircraft_type' => 'Airbus A320',
                'origin_country_id' => $bangladeshId,
                'origin_city' => 'Chittagong',
                'origin_airport' => 'Shah Amanat International Airport',
                'origin_airport_code' => 'CGP',
                'destination_country_id' => Country::where('iso_code_2', 'MY')->first()->id,
                'destination_city' => 'Kuala Lumpur',
                'destination_airport' => 'Kuala Lumpur International Airport 2',
                'destination_airport_code' => 'KUL',
                'departure_time' => '16:30:00',
                'arrival_time' => '22:45:00',
                'flight_duration' => '3h 15m',
                'available_days' => ['tuesday', 'thursday', 'saturday'],
                'is_direct' => true,
                'stops' => 0,
                'economy_price' => 19000,
                'currency_id' => $bdtCurrencyId,
                'total_seats' => 180,
                'economy_seats' => 180,
                'cabin_baggage' => '7kg',
                'checked_baggage' => '20kg',
                'extra_baggage_price' => '৳1200 per 5kg',
                'amenities' => ['buy-on-board'],
                'meal_type' => 'Buy on Board',
                'has_wifi' => false,
                'has_entertainment' => false,
                'booking_fee' => 300,
                'cancellation_fee_percentage' => 15,
                'is_popular' => false,
                'display_order' => 10,
                'description' => 'Low-cost flights to Malaysia from Chittagong. Great value for budget travelers.',
                'tags' => ['worker-friendly', 'budget', 'direct-flight'],
            ],
        ];

        foreach ($routes as $routeData) {
            FlightRoute::create($routeData);
        }

        $this->command->info('✅ Created ' . count($routes) . ' flight routes successfully!');
    }
}
