<?php

namespace Database\Seeders;

use App\Models\JobPosting;
use App\Models\Country;
use Illuminate\Database\Seeder;

class JobPostingSeeder extends Seeder
{
    public function run(): void
    {
        // Get popular destination countries
        $uae = Country::where('name', 'United Arab Emirates')->first();
        $saudiArabia = Country::where('name', 'Saudi Arabia')->first();
        $qatar = Country::where('name', 'Qatar')->first();
        $kuwait = Country::where('name', 'Kuwait')->first();
        $malaysia = Country::where('name', 'Malaysia')->first();
        $singapore = Country::where('name', 'Singapore')->first();

        $jobs = [
            // UAE Jobs
            [
                'title' => 'Hotel Waiter - Fine Dining',
                'slug' => 'hotel-waiter-fine-dining-dubai',
                'company_name' => 'Ritz Carlton Dubai',
                'country_id' => $uae->id,
                'city' => 'Dubai',
                'job_type' => 'full_time',
                'category' => 'Hospitality',
                'description' => 'Join our world-class fine dining restaurant as a waiter. Serve international guests with exceptional service standards.',
                'responsibilities' => 'Take orders, serve food and beverages, maintain cleanliness, handle customer queries',
                'requirements' => 'Experience in fine dining, English proficiency, professional appearance',
                'benefits' => json_encode(['Free accommodation', 'Free meals', 'Health insurance', 'Annual leave']),
                'skills' => json_encode(['English', 'Customer Service']),
                'salary_min' => 1800,
                'salary_max' => 2200,
                'salary_currency' => 'AED',
                'positions_available' => 5,
                'experience_years' => 2,
                'education_level' => 'High School',
                'gender_preference' => 'male',
                'age_min' => 21,
                'age_max' => 35,
                'application_fee' => 500,
                'is_featured' => true,
                'is_active' => true,
                'application_deadline' => now()->addDays(28),
                'published_at' => now()->subDays(2),
            ],
            
            [
                'title' => 'Housekeeping Staff - 5 Star Hotel',
                'slug' => 'housekeeping-staff-marriott-dubai',
                'company_name' => 'Marriott Dubai',
                'country_id' => $uae->id,
                'city' => 'Dubai',
                'job_type' => 'full_time',
                'category' => 'Hospitality',
                'description' => 'Maintain cleanliness and hygiene standards in our luxury hotel rooms and common areas.',
                'responsibilities' => 'Clean guest rooms, change linens, restock amenities, report maintenance issues',
                'requirements' => 'Basic English, attention to detail, physical fitness',
                'benefits' => json_encode(['Free accommodation', 'Free meals', 'Health insurance']),
                'skills' => json_encode(['Cleaning', 'Physical Fitness']),
                'salary_min' => 1400,
                'salary_max' => 1700,
                'salary_currency' => 'AED',
                'positions_available' => 10,
                'experience_years' => 0,
                'education_level' => 'Primary',
                'gender_preference' => 'any',
                'age_min' => 21,
                'age_max' => 40,
                'application_fee' => 300,
                'is_featured' => true,
                'is_active' => true,
                'application_deadline' => now()->addDays(25),
                'published_at' => now()->subDays(5),
            ],
            
            [
                'title' => 'Electrician - Commercial Projects',
                'slug' => 'electrician-alfuttaim-abu-dhabi',
                'company_name' => 'Al Futtaim Engineering',
                'country_id' => $uae->id,
                'city' => 'Abu Dhabi',
                'job_type' => 'full_time',
                'category' => 'Construction',
                'description' => 'Install, maintain and repair electrical systems in commercial buildings.',
                'responsibilities' => 'Install wiring, troubleshoot electrical issues, read technical drawings',
                'requirements' => 'Electrician certification, 3+ years experience, blueprint reading',
                'benefits' => json_encode(['Free accommodation', 'Transport allowance', 'Medical insurance']),
                'skills' => json_encode(['Electrical Work', 'Blueprint Reading']),
                'salary_min' => 2500,
                'salary_max' => 3200,
                'salary_currency' => 'AED',
                'positions_available' => 3,
                'experience_years' => 3,
                'education_level' => 'Technical Diploma',
                'gender_preference' => 'male',
                'age_min' => 25,
                'age_max' => 45,
                'application_fee' => 800,
                'is_featured' => true,
                'is_active' => true,
                'application_deadline' => now()->addDays(30),
                'published_at' => now()->subDays(1),
            ],
            
            // Saudi Arabia Jobs
            [
                'title' => 'Construction Worker - Building Projects',
                'slug' => 'construction-worker-riyadh',
                'company_name' => 'Saudi Construction Co.',
                'country_id' => $saudiArabia->id,
                'city' => 'Riyadh',
                'job_type' => 'contract',
                'category' => 'Construction',
                'description' => 'Work on major construction projects in Riyadh. 2-year contract.',
                'responsibilities' => 'General construction work, material handling, site preparation',
                'requirements' => 'Physical fitness, construction experience preferred',
                'benefits' => json_encode(['Free accommodation', 'Free transport', 'Overtime pay']),
                'skills' => json_encode(['Physical Fitness', 'Construction']),
                'salary_min' => 1500,
                'salary_max' => 1800,
                'salary_currency' => 'SAR',
                'positions_available' => 20,
                'experience_years' => 1,
                'education_level' => 'No requirement',
                'gender_preference' => 'male',
                'age_min' => 21,
                'age_max' => 45,
                'application_fee' => 400,
                'is_featured' => false,
                'is_active' => true,
                'application_deadline' => now()->addDays(20),
                'published_at' => now()->subDays(3),
            ],
            
            [
                'title' => 'Heavy Vehicle Driver - Trucks',
                'slug' => 'truck-driver-jeddah',
                'company_name' => 'Saudi Transport LLC',
                'country_id' => $saudiArabia->id,
                'city' => 'Jeddah',
                'job_type' => 'full_time',
                'category' => 'Transportation',
                'description' => 'Drive heavy trucks for cargo transportation across Saudi Arabia.',
                'responsibilities' => 'Safe driving, cargo loading/unloading, vehicle maintenance',
                'requirements' => 'Valid heavy vehicle license, 3+ years driving experience',
                'benefits' => json_encode(['Free accommodation', 'Fuel allowance', 'Medical insurance']),
                'skills' => json_encode(['Heavy Vehicle Driving', 'Navigation']),
                'salary_min' => 2000,
                'salary_max' => 2500,
                'salary_currency' => 'SAR',
                'positions_available' => 8,
                'experience_years' => 3,
                'education_level' => 'High School',
                'gender_preference' => 'male',
                'age_min' => 25,
                'age_max' => 50,
                'application_fee' => 800,
                'is_featured' => false,
                'is_active' => true,
                'application_deadline' => now()->addDays(26),
                'published_at' => now()->subDays(4),
            ],
            
            // Qatar Jobs
            [
                'title' => 'Sales Associate - Luxury Retail',
                'slug' => 'sales-associate-luxury-doha',
                'company_name' => 'Luxury Brands Qatar',
                'country_id' => $qatar->id,
                'city' => 'Doha',
                'job_type' => 'full_time',
                'category' => 'Retail',
                'description' => 'Represent our luxury brand in our flagship store. Commission-based incentives.',
                'responsibilities' => 'Customer service, product knowledge, sales targets, inventory management',
                'requirements' => 'Fluent English, retail experience, professional appearance',
                'benefits' => json_encode(['Accommodation allowance', 'Sales commission', 'Medical insurance']),
                'skills' => json_encode(['English', 'Sales', 'Customer Service']),
                'salary_min' => 3000,
                'salary_max' => 4000,
                'salary_currency' => 'QAR',
                'positions_available' => 3,
                'experience_years' => 2,
                'education_level' => "Bachelor's Degree",
                'gender_preference' => 'female',
                'age_min' => 23,
                'age_max' => 35,
                'application_fee' => 500,
                'is_featured' => true,
                'is_active' => true,
                'application_deadline' => now()->addDays(27),
                'published_at' => now()->subDays(3),
            ],
            
            // Kuwait Jobs
            [
                'title' => 'Registered Nurse - General Ward',
                'slug' => 'nurse-kuwait-hospital',
                'company_name' => 'Kuwait International Hospital',
                'country_id' => $kuwait->id,
                'city' => 'Kuwait City',
                'job_type' => 'full_time',
                'category' => 'Healthcare',
                'description' => 'Provide nursing care in our general medical ward.',
                'responsibilities' => 'Patient care, medication administration, vital signs monitoring',
                'requirements' => 'RN license, 2+ years experience, excellent English',
                'benefits' => json_encode(['Free accommodation', 'Annual airfare', '30 days annual leave']),
                'skills' => json_encode(['Nursing', 'English', 'Patient Care', 'BLS']),
                'salary_min' => 800,
                'salary_max' => 1000,
                'salary_currency' => 'KWD',
                'positions_available' => 4,
                'experience_years' => 2,
                'education_level' => "Bachelor's Degree",
                'gender_preference' => 'any',
                'age_min' => 23,
                'age_max' => 45,
                'application_fee' => 1000,
                'is_featured' => true,
                'is_active' => true,
                'application_deadline' => now()->addDays(15),
                'published_at' => now()->subDays(4),
            ],
            
            [
                'title' => 'English Teacher - International School',
                'slug' => 'english-teacher-kuwait',
                'company_name' => 'British School Kuwait',
                'country_id' => $kuwait->id,
                'city' => 'Kuwait City',
                'job_type' => 'full_time',
                'category' => 'Education',
                'description' => 'Teach English to students aged 11-16. Follow British curriculum.',
                'responsibilities' => 'Lesson planning, teaching, assessment, parent meetings',
                'requirements' => 'B.Ed/M.Ed degree, 3+ years teaching experience, native English',
                'benefits' => json_encode(['Free accommodation', 'Annual airfare', '2 months vacation']),
                'skills' => json_encode(['Teaching', 'English', 'Curriculum Development']),
                'salary_min' => 1200,
                'salary_max' => 1600,
                'salary_currency' => 'KWD',
                'positions_available' => 2,
                'experience_years' => 3,
                'education_level' => "Master's Degree",
                'gender_preference' => 'any',
                'age_min' => 25,
                'age_max' => 55,
                'application_fee' => 0,
                'is_featured' => true,
                'is_active' => true,
                'application_deadline' => now()->addDays(20),
                'published_at' => now()->subDays(6),
            ],
            
            // Malaysia Jobs
            [
                'title' => 'Factory Worker - Electronics Assembly',
                'slug' => 'factory-worker-electronics-penang',
                'company_name' => 'Flex Malaysia',
                'country_id' => $malaysia->id,
                'city' => 'Penang',
                'job_type' => 'full_time',
                'category' => 'Manufacturing',
                'description' => 'Assemble electronic components in our modern manufacturing facility.',
                'responsibilities' => 'Component assembly, quality inspection, equipment operation',
                'requirements' => 'Good eyesight, attention to detail, ability to work shifts',
                'benefits' => json_encode(['Free accommodation', 'Transport provided', 'Overtime opportunities']),
                'skills' => json_encode(['Attention to Detail', 'Manual Dexterity']),
                'salary_min' => 1600,
                'salary_max' => 2000,
                'salary_currency' => 'MYR',
                'positions_available' => 15,
                'experience_years' => 0,
                'education_level' => 'High School',
                'gender_preference' => 'any',
                'age_min' => 21,
                'age_max' => 40,
                'application_fee' => 700,
                'is_featured' => false,
                'is_active' => true,
                'application_deadline' => now()->addDays(23),
                'published_at' => now()->subDays(7),
            ],
            
            // Singapore Jobs
            [
                'title' => 'Software Developer - Full Stack',
                'slug' => 'software-developer-singapore',
                'company_name' => 'Tech Solutions Singapore',
                'country_id' => $singapore->id,
                'city' => 'Singapore',
                'job_type' => 'full_time',
                'category' => 'IT',
                'description' => 'Develop and maintain web applications using modern tech stack.',
                'responsibilities' => 'Full stack development, code reviews, testing, deployment',
                'requirements' => 'Computer Science degree, React/Vue.js, Laravel/Node.js, Git',
                'benefits' => json_encode(['Housing allowance', 'Medical insurance', 'Flexible hours']),
                'skills' => json_encode(['React', 'Laravel', 'MySQL', 'Git']),
                'salary_min' => 5000,
                'salary_max' => 7000,
                'salary_currency' => 'SGD',
                'positions_available' => 2,
                'experience_years' => 3,
                'education_level' => "Bachelor's Degree",
                'gender_preference' => 'any',
                'age_min' => 23,
                'age_max' => 40,
                'application_fee' => 0,
                'is_featured' => true,
                'is_active' => true,
                'application_deadline' => now()->addDays(30),
                'published_at' => now()->subDays(1),
            ],
        ];

        foreach ($jobs as $job) {
            JobPosting::create($job);
        }

        $this->command->info('✅ Created ' . count($jobs) . ' job postings successfully!');
    }
}
