<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ServiceModule;
use App\Models\ServiceCategory;

class ServiceModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * The "Plugin System" - Each service is a cartridge that can be plugged into agencies
     */
    public function run(): void
    {
        $categories = [
            'visa' => ServiceCategory::where('slug', 'visa')->first(),
            'travel' => ServiceCategory::where('slug', 'travel')->first(),
            'education' => ServiceCategory::where('slug', 'education')->first(),
            'employment' => ServiceCategory::where('slug', 'employment')->first(),
            'documents' => ServiceCategory::where('slug', 'documents')->first(),
            'financial' => ServiceCategory::where('slug', 'financial')->first(),
            'other' => ServiceCategory::where('slug', 'other')->first(),
        ];

        $services = [
            // ========================================
            // VISA SERVICES (Competitive Model)
            // Multiple agencies compete for same countries
            // ========================================
            [
                'service_category_id' => $categories['visa']->id,
                'name' => 'Tourist Visa',
                'slug' => 'tourist-visa',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Apply for tourist visas to 100+ countries',
                'full_description' => 'Professional tourist visa processing with expert guidance, document preparation, and application tracking.',
                'is_active' => true,
                'coming_soon' => false,
                'price_type' => 'quote',
                'platform_commission_rate' => 15.00,
                'allows_multiple_agencies' => true,
                'requires_admin_approval' => false,
                'resource_locking' => false,
                'requires_agency' => true,
                'quote_timeout_hours' => 24,
                'min_quotes_required' => 1,
                'route_prefix' => '/services/tourist-visa',
                'controller' => 'TouristVisaController',
                'sort_order' => 1,
            ],
            [
                'service_category_id' => $categories['visa']->id,
                'name' => 'Student Visa',
                'slug' => 'student-visa',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Study abroad visa and university admission assistance',
                'full_description' => 'Complete student visa processing including university selection, admission guidance, document preparation, and visa application support for studying abroad.',
                'is_active' => true,
                'coming_soon' => false,
                'price_type' => 'quote',
                'platform_commission_rate' => 18.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'quote_timeout_hours' => 48,
                'min_quotes_required' => 2,
                'sort_order' => 2,
            ],
            [
                'service_category_id' => $categories['visa']->id,
                'name' => 'Work Visa',
                'slug' => 'work-visa',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Work permit and employment visa processing',
                'full_description' => 'Comprehensive work visa services including job placement assistance, employer sponsorship coordination, LMIA/labor certification, work permit applications, and employment visa processing for various countries.',
                'is_active' => true,
                'coming_soon' => false,
                'price_type' => 'quote',
                'platform_commission_rate' => 20.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'quote_timeout_hours' => 48,
                'sort_order' => 3,
            ],
            [
                'service_category_id' => $categories['visa']->id,
                'name' => 'Business Visa',
                'slug' => 'business-visa',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Business travel and investor visa services',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 18.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 4,
            ],
            [
                'service_category_id' => $categories['visa']->id,
                'name' => 'Medical Visa',
                'slug' => 'medical-visa',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Medical treatment visa and hospital coordination',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 15.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 5,
            ],
            [
                'service_category_id' => $categories['visa']->id,
                'name' => 'Family Reunion Visa',
                'slug' => 'family-reunion-visa',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Family sponsorship and reunion visa processing',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 18.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 6,
            ],

            // ========================================
            // TRAVEL SERVICES
            // ========================================
            [
                'service_category_id' => $categories['travel']->id,
                'name' => 'Flight Booking',
                'slug' => 'flight-booking',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Book international and domestic flights',
                'is_active' => true,
                'coming_soon' => false,
                'price_type' => 'quote',
                'platform_commission_rate' => 8.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'quote_timeout_hours' => 12,
                'min_quotes_required' => 2,
                'sort_order' => 7,
            ],
            [
                'service_category_id' => $categories['travel']->id,
                'name' => 'Hotel Booking',
                'slug' => 'hotel-booking',
                'service_type' => 'hybrid',
                'assignment_model' => 'hybrid',
                'short_description' => 'Book hotels worldwide with special requests support',
                'is_active' => true,
                'coming_soon' => false,
                'price_type' => 'quote',
                'platform_commission_rate' => 10.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => false,
                'quote_timeout_hours' => 6,
                'sort_order' => 8,
            ],
            [
                'service_category_id' => $categories['travel']->id,
                'name' => 'Travel Insurance',
                'slug' => 'travel-insurance',
                'service_type' => 'api_based',
                'assignment_model' => 'global_single',
                'short_description' => 'Comprehensive travel insurance coverage',
                'is_active' => true,
                'coming_soon' => false,
                'price_type' => 'fixed',
                'platform_commission_rate' => 12.00,
                'allows_multiple_agencies' => false,
                'requires_agency' => true,
                'quote_timeout_hours' => 1,
                'sort_order' => 9,
            ],
            [
                'service_category_id' => $categories['travel']->id,
                'name' => 'Tour Packages',
                'slug' => 'tour-packages',
                'service_type' => 'query_based',
                'assignment_model' => 'multi_country',
                'short_description' => 'Customized tour packages and group travel',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 15.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 10,
            ],
            [
                'service_category_id' => $categories['travel']->id,
                'name' => 'Airport Transfer',
                'slug' => 'airport-transfer',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Airport pickup and drop-off services',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 10.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 11,
            ],

            // ========================================
            // EDUCATION SERVICES (Exclusive Resource Model)
            // First agency to add a university owns it
            // ========================================
            [
                'service_category_id' => $categories['education']->id,
                'name' => 'University Application',
                'slug' => 'university-application',
                'service_type' => 'query_based',
                'assignment_model' => 'exclusive_resource',
                'short_description' => 'Apply to universities worldwide with expert guidance',
                'full_description' => 'Complete university application support including university selection, document preparation, application submission, and acceptance tracking.',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 25.00,
                'allows_multiple_agencies' => false,
                'requires_admin_approval' => true,
                'resource_locking' => true,
                'requires_agency' => true,
                'quote_timeout_hours' => 72,
                'min_quotes_required' => 1,
                'sort_order' => 12,
            ],
            [
                'service_category_id' => $categories['education']->id,
                'name' => 'School Application',
                'slug' => 'school-application',
                'service_type' => 'query_based',
                'assignment_model' => 'exclusive_resource',
                'short_description' => 'School and college application assistance',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 22.00,
                'allows_multiple_agencies' => false,
                'requires_admin_approval' => true,
                'resource_locking' => true,
                'requires_agency' => true,
                'sort_order' => 13,
            ],
            [
                'service_category_id' => $categories['education']->id,
                'name' => 'Language Course',
                'slug' => 'language-course',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Language course enrollment and preparation',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 18.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 14,
            ],
            [
                'service_category_id' => $categories['education']->id,
                'name' => 'Scholarship Assistance',
                'slug' => 'scholarship-assistance',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Find and apply for scholarships',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 20.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 15,
            ],
            [
                'service_category_id' => $categories['education']->id,
                'name' => 'Education Loan',
                'slug' => 'education-loan',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Student loan and financial aid assistance',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 15.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 16,
            ],
            [
                'service_category_id' => $categories['education']->id,
                'name' => 'Student Accommodation',
                'slug' => 'student-accommodation',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Find student housing and accommodation',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 12.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 17,
            ],

            // ========================================
            // EMPLOYMENT SERVICES (Multi-Country Model)
            // Agencies handle multiple countries
            // ========================================
            [
                'service_category_id' => $categories['employment']->id,
                'name' => 'Job Posting',
                'slug' => 'job-posting',
                'service_type' => 'marketplace',
                'assignment_model' => 'multi_country',
                'short_description' => 'Post jobs and find candidates worldwide',
                'is_active' => true,
                'coming_soon' => false,
                'price_type' => 'quote',
                'platform_commission_rate' => 10.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'quote_timeout_hours' => 48,
                'sort_order' => 18,
            ],
            [
                'service_category_id' => $categories['employment']->id,
                'name' => 'Job Application Assistance',
                'slug' => 'job-application-assistance',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Professional help with job applications',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 15.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 19,
            ],
            [
                'service_category_id' => $categories['employment']->id,
                'name' => 'CV Building',
                'slug' => 'cv-building',
                'service_type' => 'premade',
                'assignment_model' => 'peer_to_peer',
                'short_description' => 'Build professional CVs with templates',
                'is_active' => true,
                'coming_soon' => false,
                'price_type' => 'free',
                'platform_commission_rate' => 0.00,
                'allows_multiple_agencies' => false,
                'requires_agency' => false,
                'sort_order' => 20,
            ],
            [
                'service_category_id' => $categories['employment']->id,
                'name' => 'Interview Preparation',
                'slug' => 'interview-preparation',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Mock interviews and career coaching',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 18.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 21,
            ],
            [
                'service_category_id' => $categories['employment']->id,
                'name' => 'Skill Verification',
                'slug' => 'skill-verification',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Professional skill assessment and certification',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 15.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 22,
            ],

            // ========================================
            // DOCUMENT SERVICES (Competitive Model)
            // Multiple specialized agencies
            // ========================================
            [
                'service_category_id' => $categories['documents']->id,
                'name' => 'Translation Services',
                'slug' => 'translation-services',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Professional document translation (50+ languages)',
                'full_description' => 'Expert translation services powered by human translators and AI, supporting 50+ languages with quality assurance.',
                'is_active' => true,
                'coming_soon' => false,
                'price_type' => 'quote',
                'platform_commission_rate' => 20.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'quote_timeout_hours' => 24,
                'min_quotes_required' => 2,
                'sort_order' => 23,
            ],
            [
                'service_category_id' => $categories['documents']->id,
                'name' => 'Document Attestation',
                'slug' => 'document-attestation',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Embassy and MOFA attestation services',
                'is_active' => true,
                'coming_soon' => false,
                'price_type' => 'quote',
                'platform_commission_rate' => 18.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'quote_timeout_hours' => 48,
                'sort_order' => 24,
            ],
            [
                'service_category_id' => $categories['documents']->id,
                'name' => 'Notary Services',
                'slug' => 'notary-services',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Legal notarization and document verification',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 15.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 25,
            ],
            [
                'service_category_id' => $categories['documents']->id,
                'name' => 'Certificate Verification',
                'slug' => 'certificate-verification',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Academic and professional certificate verification',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 12.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 26,
            ],
            [
                'service_category_id' => $categories['documents']->id,
                'name' => 'Police Clearance',
                'slug' => 'police-clearance',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Police clearance certificate processing',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 15.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 27,
            ],
            [
                'service_category_id' => $categories['documents']->id,
                'name' => 'Medical Certificate',
                'slug' => 'medical-certificate',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Medical fitness certificates for employment',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 10.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 28,
            ],

            // ========================================
            // FINANCIAL SERVICES
            // ========================================
            [
                'service_category_id' => $categories['financial']->id ?? $categories['other']->id,
                'name' => 'Foreign Exchange',
                'slug' => 'foreign-exchange',
                'service_type' => 'api_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Currency exchange and money transfer',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 3.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 29,
            ],
            [
                'service_category_id' => $categories['financial']->id ?? $categories['other']->id,
                'name' => 'Travel Money Card',
                'slug' => 'travel-money-card',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Prepaid forex cards for international travel',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 8.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 30,
            ],
            [
                'service_category_id' => $categories['financial']->id ?? $categories['other']->id,
                'name' => 'Bank Account Opening',
                'slug' => 'bank-account-opening',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'International bank account setup assistance',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 12.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 31,
            ],

            // ========================================
            // OTHER SERVICES
            // ========================================
            [
                'service_category_id' => $categories['other']->id,
                'name' => 'Hajj & Umrah',
                'slug' => 'hajj-umrah',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Complete Hajj and Umrah pilgrimage packages',
                'full_description' => 'Comprehensive pilgrimage packages including visa, accommodation, transportation, and spiritual guidance for Hajj and Umrah.',
                'is_active' => true,
                'coming_soon' => false,
                'price_type' => 'quote',
                'platform_commission_rate' => 12.00,
                'allows_multiple_agencies' => true,
                'requires_admin_approval' => true,
                'requires_agency' => true,
                'quote_timeout_hours' => 72,
                'sort_order' => 32,
            ],
            [
                'service_category_id' => $categories['other']->id,
                'name' => 'Medical Tourism',
                'slug' => 'medical-tourism',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Medical treatment abroad with full support',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 15.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 33,
            ],
            [
                'service_category_id' => $categories['other']->id,
                'name' => 'Relocation Services',
                'slug' => 'relocation-services',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Complete relocation and settling assistance',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 18.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 34,
            ],
            [
                'service_category_id' => $categories['other']->id,
                'name' => 'SIM Card & Internet',
                'slug' => 'sim-card-internet',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'International SIM cards and internet connectivity',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 8.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 35,
            ],
            [
                'service_category_id' => $categories['other']->id,
                'name' => 'Legal Consultation',
                'slug' => 'legal-consultation',
                'service_type' => 'query_based',
                'assignment_model' => 'competitive',
                'short_description' => 'Immigration and legal advice services',
                'is_active' => false,
                'coming_soon' => true,
                'price_type' => 'quote',
                'platform_commission_rate' => 20.00,
                'allows_multiple_agencies' => true,
                'requires_agency' => true,
                'sort_order' => 36,
            ],
        ];

        foreach ($services as $service) {
            ServiceModule::updateOrCreate(
                ['slug' => $service['slug']],
                $service
            );
        }

        $this->command->info('✅ 36 Service Modules (Plugins) seeded successfully!');
        $this->command->info('   - 6 Visa Services');
        $this->command->info('   - 5 Travel Services');
        $this->command->info('   - 6 Education Services');
        $this->command->info('   - 5 Employment Services');
        $this->command->info('   - 6 Document Services');
        $this->command->info('   - 3 Financial Services');
        $this->command->info('   - 5 Other Services');
        $this->command->info('');
        $this->command->info('💡 Assignment Models:');
        $this->command->info('   - Competitive: Multiple agencies compete (visas, translation)');
        $this->command->info('   - Exclusive Resource: First agency owns resource (universities)');
        $this->command->info('   - Global Single: One agency worldwide (insurance)');
        $this->command->info('   - Multi-Country: Regional specialists (jobs)');
        $this->command->info('   - Hybrid: API + Agency (hotels)');
        $this->command->info('   - Peer-to-Peer: No agency (CV builder)');
    }
}
