<?php

namespace Database\Seeders;

use App\Models\TravelInsurancePackage;
use Illuminate\Database\Seeder;

class TravelInsurancePackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        echo "🛡️ Creating Travel Insurance Packages...\n";

        $packages = [
            [
                'name' => 'Basic Travel Shield',
                'slug' => 'basic-travel-shield',
                'description' => 'Essential coverage for budget travelers. Perfect for short trips with basic medical and baggage protection.',
                'features' => [
                    'Medical expenses up to ৳5,00,000',
                    'Lost baggage coverage ৳50,000',
                    'Trip cancellation up to ৳30,000',
                    'Emergency evacuation',
                    '24/7 customer support',
                ],
                'price_per_day' => 150.00,
                'min_price' => 500.00,
                'max_coverage' => 500000.00,
                'min_days' => 1,
                'max_days' => 30,
                'min_age' => 1,
                'max_age' => 70,
                'covered_countries' => 'all', // All countries
                'coverage_details' => [
                    'medical_expenses' => 500000,
                    'baggage_loss' => 50000,
                    'trip_cancellation' => 30000,
                    'personal_accident' => 200000,
                    'emergency_evacuation' => true,
                ],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 1,
                'badge_text' => 'Budget Friendly',
                'badge_color' => 'blue',
            ],
            [
                'name' => 'Standard Explorer',
                'slug' => 'standard-explorer',
                'description' => 'Comprehensive protection for the average traveler. Includes enhanced medical coverage and trip delay benefits.',
                'features' => [
                    'Medical expenses up to ৳15,00,000',
                    'Lost baggage coverage ৳1,00,000',
                    'Trip cancellation up to ৳75,000',
                    'Trip delay compensation',
                    'Flight accident coverage',
                    'Emergency evacuation & repatriation',
                    '24/7 multilingual support',
                ],
                'price_per_day' => 300.00,
                'min_price' => 1200.00,
                'max_coverage' => 1500000.00,
                'min_days' => 1,
                'max_days' => 90,
                'min_age' => 1,
                'max_age' => 75,
                'covered_countries' => 'all',
                'coverage_details' => [
                    'medical_expenses' => 1500000,
                    'baggage_loss' => 100000,
                    'trip_cancellation' => 75000,
                    'personal_accident' => 500000,
                    'trip_delay' => 20000,
                    'flight_accident' => 1000000,
                    'emergency_evacuation' => true,
                ],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 2,
                'badge_text' => 'Most Popular',
                'badge_color' => 'emerald',
            ],
            [
                'name' => 'Premium Global',
                'slug' => 'premium-global',
                'description' => 'Maximum protection for frequent travelers and long-term trips. Premium benefits with highest coverage limits.',
                'features' => [
                    'Medical expenses up to ৳50,00,000',
                    'Lost baggage coverage ৳2,00,000',
                    'Trip cancellation up to ৳2,00,000',
                    'Trip interruption coverage',
                    'Rental car damage coverage',
                    'Adventure sports coverage',
                    'COVID-19 medical expenses',
                    'Emergency evacuation & repatriation',
                    'Priority 24/7 concierge service',
                ],
                'price_per_day' => 600.00,
                'min_price' => 3000.00,
                'max_coverage' => 5000000.00,
                'min_days' => 1,
                'max_days' => 180,
                'min_age' => 1,
                'max_age' => 80,
                'covered_countries' => 'all',
                'coverage_details' => [
                    'medical_expenses' => 5000000,
                    'baggage_loss' => 200000,
                    'trip_cancellation' => 200000,
                    'trip_interruption' => 150000,
                    'personal_accident' => 1000000,
                    'trip_delay' => 50000,
                    'flight_accident' => 2000000,
                    'rental_car_damage' => 100000,
                    'adventure_sports' => true,
                    'covid_coverage' => true,
                    'emergency_evacuation' => true,
                ],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 3,
                'badge_text' => 'Best Coverage',
                'badge_color' => 'amber',
            ],
            [
                'name' => 'Hajj & Umrah Special',
                'slug' => 'hajj-umrah-special',
                'description' => 'Specialized coverage for pilgrims traveling to Saudi Arabia. Tailored for Hajj and Umrah requirements.',
                'features' => [
                    'Medical expenses up to ৳20,00,000',
                    'Lost baggage coverage ৳1,50,000',
                    'Ihram damage coverage',
                    'Missed Hajj/Umrah due to illness',
                    'Emergency evacuation from Makkah/Madinah',
                    'Arabic-speaking support team',
                    '24/7 emergency helpline',
                ],
                'price_per_day' => 400.00,
                'min_price' => 8000.00,
                'max_coverage' => 2000000.00,
                'min_days' => 20,
                'max_days' => 45,
                'min_age' => 18,
                'max_age' => 75,
                'covered_countries' => ['SA'], // Saudi Arabia only
                'coverage_details' => [
                    'medical_expenses' => 2000000,
                    'baggage_loss' => 150000,
                    'ihram_damage' => 10000,
                    'missed_pilgrimage' => 50000,
                    'personal_accident' => 500000,
                    'emergency_evacuation' => true,
                    'arabic_support' => true,
                ],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 4,
                'badge_text' => 'Hajj/Umrah',
                'badge_color' => 'purple',
            ],
            [
                'name' => 'Student Abroad',
                'slug' => 'student-abroad',
                'description' => 'Long-term coverage designed for students studying overseas. Includes study interruption and tuition fee protection.',
                'features' => [
                    'Medical expenses up to ৳30,00,000',
                    'Lost baggage & laptop coverage ৳1,50,000',
                    'Study interruption coverage',
                    'Tuition fee protection',
                    'Accommodation coverage',
                    'Mental health support',
                    'Emergency return home',
                    '24/7 student helpline',
                ],
                'price_per_day' => 350.00,
                'min_price' => 42000.00, // ~4 months minimum
                'max_coverage' => 3000000.00,
                'min_days' => 120,
                'max_days' => 365,
                'min_age' => 16,
                'max_age' => 35,
                'covered_countries' => 'all',
                'coverage_details' => [
                    'medical_expenses' => 3000000,
                    'baggage_loss' => 150000,
                    'study_interruption' => 100000,
                    'tuition_protection' => 200000,
                    'accommodation' => 50000,
                    'personal_accident' => 500000,
                    'mental_health' => true,
                    'emergency_evacuation' => true,
                ],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 5,
                'badge_text' => 'Student Plan',
                'badge_color' => 'indigo',
            ],
            [
                'name' => 'Business Traveler Pro',
                'slug' => 'business-traveler-pro',
                'description' => 'Executive coverage for business professionals. Includes business equipment and document loss protection.',
                'features' => [
                    'Medical expenses up to ৳40,00,000',
                    'Business equipment coverage ৳3,00,000',
                    'Important documents replacement',
                    'Business trip cancellation up to ৳2,50,000',
                    'Rental car excess coverage',
                    'Legal liability coverage',
                    'Priority airport lounge access',
                    '24/7 executive support',
                ],
                'price_per_day' => 750.00,
                'min_price' => 2500.00,
                'max_coverage' => 4000000.00,
                'min_days' => 1,
                'max_days' => 120,
                'min_age' => 21,
                'max_age' => 70,
                'covered_countries' => 'all',
                'coverage_details' => [
                    'medical_expenses' => 4000000,
                    'business_equipment' => 300000,
                    'trip_cancellation' => 250000,
                    'documents_loss' => 50000,
                    'personal_accident' => 1500000,
                    'rental_car_excess' => 75000,
                    'legal_liability' => 500000,
                    'emergency_evacuation' => true,
                ],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 6,
                'badge_text' => 'Business',
                'badge_color' => 'slate',
            ],
        ];

        foreach ($packages as $package) {
            TravelInsurancePackage::create($package);
            echo "  ✓ {$package['name']} - ৳{$package['price_per_day']}/day\n";
        }

        echo "\n✅ Created " . count($packages) . " travel insurance packages\n";
    }
}
