<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\University;
use Illuminate\Database\Seeder;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get countries
        $usa = Country::where('name', 'United States')->first();
        $uk = Country::where('name', 'United Kingdom')->first();
        $canada = Country::where('name', 'Canada')->first();
        $australia = Country::where('name', 'Australia')->first();
        $germany = Country::where('name', 'Germany')->first();

        if (! $usa || ! $uk || ! $canada || ! $australia || ! $germany) {
            $this->command->error('Required countries not found. Please seed countries first.');

            return;
        }

        $universities = [
            // USA Universities
            [
                'name' => 'Massachusetts Institute of Technology (MIT)',
                'country_id' => $usa->id,
                'city' => 'Cambridge',
                'state' => 'Massachusetts',
                'world_ranking' => 1,
                'country_ranking' => 1,
                'tuition_min' => 53790,
                'tuition_max' => 57590,
                'website' => 'https://www.mit.edu',
                'established_year' => 1861,
                'type' => 'private',
                'acceptance_rate' => 3.9,
                'student_count' => 11934,
                'international_students' => 3748,
                'scholarships_available' => true,
                'application_fee' => 85,
                'description' => 'MIT is a world-renowned research university known for its leadership in science, technology, and engineering.',
                'programs' => ['Engineering', 'Computer Science', 'Physics', 'Mathematics', 'Economics'],
                'popular_majors' => ['Computer Science', 'Mechanical Engineering', 'Mathematics', 'Physics', 'Electrical Engineering'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Stanford University',
                'country_id' => $usa->id,
                'city' => 'Stanford',
                'state' => 'California',
                'world_ranking' => 2,
                'country_ranking' => 2,
                'tuition_min' => 56169,
                'tuition_max' => 58416,
                'website' => 'https://www.stanford.edu',
                'established_year' => 1885,
                'type' => 'private',
                'acceptance_rate' => 3.7,
                'student_count' => 17249,
                'international_students' => 3879,
                'scholarships_available' => true,
                'application_fee' => 90,
                'description' => 'Stanford University is a leading research university with seven schools, known for its entrepreneurial spirit.',
                'programs' => ['Business', 'Computer Science', 'Law', 'Medicine', 'Engineering'],
                'popular_majors' => ['Computer Science', 'Engineering', 'Biology', 'Economics', 'Psychology'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Harvard University',
                'country_id' => $usa->id,
                'city' => 'Cambridge',
                'state' => 'Massachusetts',
                'world_ranking' => 3,
                'country_ranking' => 3,
                'tuition_min' => 54269,
                'tuition_max' => 57261,
                'website' => 'https://www.harvard.edu',
                'established_year' => 1636,
                'type' => 'private',
                'acceptance_rate' => 3.4,
                'student_count' => 23731,
                'international_students' => 5877,
                'scholarships_available' => true,
                'application_fee' => 85,
                'description' => 'Harvard is the oldest institution of higher learning in the United States, renowned globally for excellence.',
                'programs' => ['Law', 'Business', 'Medicine', 'Arts & Sciences', 'Engineering'],
                'popular_majors' => ['Economics', 'Government', 'Computer Science', 'Psychology', 'Biology'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'California Institute of Technology (Caltech)',
                'country_id' => $usa->id,
                'city' => 'Pasadena',
                'state' => 'California',
                'world_ranking' => 6,
                'country_ranking' => 4,
                'tuition_min' => 56364,
                'tuition_max' => 58479,
                'website' => 'https://www.caltech.edu',
                'established_year' => 1891,
                'type' => 'private',
                'acceptance_rate' => 3.9,
                'student_count' => 2397,
                'international_students' => 743,
                'scholarships_available' => true,
                'application_fee' => 75,
                'description' => 'Caltech is a world-renowned science and engineering institute focused on research and innovation.',
                'programs' => ['Physics', 'Chemistry', 'Biology', 'Engineering', 'Mathematics'],
                'popular_majors' => ['Physics', 'Computer Science', 'Chemical Engineering', 'Mathematics', 'Biology'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'University of Chicago',
                'country_id' => $usa->id,
                'city' => 'Chicago',
                'state' => 'Illinois',
                'world_ranking' => 10,
                'country_ranking' => 5,
                'tuition_min' => 60552,
                'tuition_max' => 62940,
                'website' => 'https://www.uchicago.edu',
                'established_year' => 1890,
                'type' => 'private',
                'acceptance_rate' => 5.4,
                'student_count' => 17834,
                'international_students' => 4234,
                'scholarships_available' => true,
                'application_fee' => 75,
                'description' => 'The University of Chicago is known for its rigorous academics and contributions to economics and social sciences.',
                'programs' => ['Economics', 'Business', 'Law', 'Medicine', 'Social Sciences'],
                'popular_majors' => ['Economics', 'Mathematics', 'Biology', 'Political Science', 'Computer Science'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Princeton University',
                'country_id' => $usa->id,
                'city' => 'Princeton',
                'state' => 'New Jersey',
                'world_ranking' => 8,
                'country_ranking' => 6,
                'tuition_min' => 56010,
                'tuition_max' => 58965,
                'website' => 'https://www.princeton.edu',
                'established_year' => 1746,
                'type' => 'private',
                'acceptance_rate' => 4.4,
                'student_count' => 8842,
                'international_students' => 2234,
                'scholarships_available' => true,
                'application_fee' => 70,
                'description' => 'Princeton is one of the oldest universities in the US, known for its undergraduate focus and research excellence.',
                'programs' => ['Engineering', 'Public Policy', 'Arts & Sciences', 'Architecture'],
                'popular_majors' => ['Economics', 'Computer Science', 'Politics', 'History', 'Psychology'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Yale University',
                'country_id' => $usa->id,
                'city' => 'New Haven',
                'state' => 'Connecticut',
                'world_ranking' => 12,
                'country_ranking' => 7,
                'tuition_min' => 59950,
                'tuition_max' => 62250,
                'website' => 'https://www.yale.edu',
                'established_year' => 1701,
                'type' => 'private',
                'acceptance_rate' => 4.6,
                'student_count' => 14567,
                'international_students' => 3456,
                'scholarships_available' => true,
                'application_fee' => 80,
                'description' => 'Yale is a prestigious Ivy League university known for its law school and liberal arts education.',
                'programs' => ['Law', 'Medicine', 'Drama', 'Art', 'Music'],
                'popular_majors' => ['Economics', 'Political Science', 'History', 'Biology', 'Psychology'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Columbia University',
                'country_id' => $usa->id,
                'city' => 'New York',
                'state' => 'New York',
                'world_ranking' => 15,
                'country_ranking' => 8,
                'tuition_min' => 63530,
                'tuition_max' => 66140,
                'website' => 'https://www.columbia.edu',
                'established_year' => 1754,
                'type' => 'private',
                'acceptance_rate' => 3.9,
                'student_count' => 33413,
                'international_students' => 9876,
                'scholarships_available' => true,
                'application_fee' => 85,
                'description' => 'Columbia is an Ivy League research university in New York City, known for journalism and international affairs.',
                'programs' => ['Journalism', 'Business', 'Law', 'Medicine', 'Engineering'],
                'popular_majors' => ['Economics', 'Political Science', 'Computer Science', 'Psychology', 'English'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'University of Pennsylvania',
                'country_id' => $usa->id,
                'city' => 'Philadelphia',
                'state' => 'Pennsylvania',
                'world_ranking' => 13,
                'country_ranking' => 9,
                'tuition_min' => 60042,
                'tuition_max' => 63452,
                'website' => 'https://www.upenn.edu',
                'established_year' => 1740,
                'type' => 'private',
                'acceptance_rate' => 5.9,
                'student_count' => 26552,
                'international_students' => 6234,
                'scholarships_available' => true,
                'application_fee' => 75,
                'description' => 'Penn is an Ivy League university with the renowned Wharton School of Business.',
                'programs' => ['Business', 'Medicine', 'Law', 'Engineering', 'Nursing'],
                'popular_majors' => ['Finance', 'Economics', 'Biology', 'Computer Science', 'Nursing'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'University of California, Berkeley',
                'country_id' => $usa->id,
                'city' => 'Berkeley',
                'state' => 'California',
                'world_ranking' => 27,
                'country_ranking' => 10,
                'tuition_min' => 14312,
                'tuition_max' => 44066,
                'website' => 'https://www.berkeley.edu',
                'established_year' => 1868,
                'type' => 'public',
                'acceptance_rate' => 11.6,
                'student_count' => 45307,
                'international_students' => 6789,
                'scholarships_available' => true,
                'application_fee' => 70,
                'description' => 'UC Berkeley is a leading public research university known for its activism and academic excellence.',
                'programs' => ['Engineering', 'Business', 'Computer Science', 'Environmental Science', 'Public Policy'],
                'popular_majors' => ['Electrical Engineering', 'Computer Science', 'Economics', 'Political Science', 'Biology'],
                'is_featured' => false,
                'is_active' => true,
            ],

            // UK Universities
            [
                'name' => 'University of Oxford',
                'country_id' => $uk->id,
                'city' => 'Oxford',
                'state' => 'England',
                'world_ranking' => 4,
                'country_ranking' => 1,
                'tuition_min' => 28370,
                'tuition_max' => 44240,
                'website' => 'https://www.ox.ac.uk',
                'established_year' => 1096,
                'type' => 'public',
                'acceptance_rate' => 17.5,
                'student_count' => 26000,
                'international_students' => 11747,
                'scholarships_available' => true,
                'application_fee' => 75,
                'description' => 'Oxford is the oldest university in the English-speaking world, renowned for its tutorial system.',
                'programs' => ['Arts', 'Sciences', 'Medicine', 'Law', 'Business'],
                'popular_majors' => ['PPE', 'Law', 'Medicine', 'History', 'English Literature'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'University of Cambridge',
                'country_id' => $uk->id,
                'city' => 'Cambridge',
                'state' => 'England',
                'world_ranking' => 5,
                'country_ranking' => 2,
                'tuition_min' => 24789,
                'tuition_max' => 63990,
                'website' => 'https://www.cam.ac.uk',
                'established_year' => 1209,
                'type' => 'public',
                'acceptance_rate' => 21.0,
                'student_count' => 24450,
                'international_students' => 9796,
                'scholarships_available' => true,
                'application_fee' => 70,
                'description' => 'Cambridge is one of the world\'s oldest and most prestigious universities, with a collegiate system.',
                'programs' => ['Natural Sciences', 'Engineering', 'Medicine', 'Law', 'Mathematics'],
                'popular_majors' => ['Natural Sciences', 'Engineering', 'Computer Science', 'Economics', 'Law'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Imperial College London',
                'country_id' => $uk->id,
                'city' => 'London',
                'state' => 'England',
                'world_ranking' => 7,
                'country_ranking' => 3,
                'tuition_min' => 35100,
                'tuition_max' => 46650,
                'website' => 'https://www.imperial.ac.uk',
                'established_year' => 1907,
                'type' => 'public',
                'acceptance_rate' => 14.3,
                'student_count' => 19945,
                'international_students' => 11234,
                'scholarships_available' => true,
                'application_fee' => 60,
                'description' => 'Imperial is a science-based institution with an international reputation for excellence in teaching and research.',
                'programs' => ['Engineering', 'Medicine', 'Natural Sciences', 'Business'],
                'popular_majors' => ['Medicine', 'Engineering', 'Computer Science', 'Chemistry', 'Physics'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'University College London (UCL)',
                'country_id' => $uk->id,
                'city' => 'London',
                'state' => 'England',
                'world_ranking' => 9,
                'country_ranking' => 4,
                'tuition_min' => 25800,
                'tuition_max' => 38000,
                'website' => 'https://www.ucl.ac.uk',
                'established_year' => 1826,
                'type' => 'public',
                'acceptance_rate' => 48.0,
                'student_count' => 46830,
                'international_students' => 23456,
                'scholarships_available' => true,
                'application_fee' => 65,
                'description' => 'UCL is London\'s leading multidisciplinary university, with a global reputation for quality research and teaching.',
                'programs' => ['Arts & Humanities', 'Engineering Sciences', 'Life Sciences', 'Social Sciences', 'Medical Sciences'],
                'popular_majors' => ['Economics', 'Law', 'Architecture', 'Computer Science', 'Psychology'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'University of Edinburgh',
                'country_id' => $uk->id,
                'city' => 'Edinburgh',
                'state' => 'Scotland',
                'world_ranking' => 22,
                'country_ranking' => 5,
                'tuition_min' => 24500,
                'tuition_max' => 34200,
                'website' => 'https://www.ed.ac.uk',
                'established_year' => 1583,
                'type' => 'public',
                'acceptance_rate' => 40.0,
                'student_count' => 35375,
                'international_students' => 18234,
                'scholarships_available' => true,
                'application_fee' => 55,
                'description' => 'The University of Edinburgh is one of Scotland\'s ancient universities, with strong research and teaching traditions.',
                'programs' => ['Medicine', 'Law', 'Business', 'Engineering', 'Arts'],
                'popular_majors' => ['Business', 'Law', 'Medicine', 'Computer Science', 'Psychology'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'King\'s College London',
                'country_id' => $uk->id,
                'city' => 'London',
                'state' => 'England',
                'world_ranking' => 33,
                'country_ranking' => 6,
                'tuition_min' => 28050,
                'tuition_max' => 46800,
                'website' => 'https://www.kcl.ac.uk',
                'established_year' => 1829,
                'type' => 'public',
                'acceptance_rate' => 13.0,
                'student_count' => 35244,
                'international_students' => 15678,
                'scholarships_available' => true,
                'application_fee' => 60,
                'description' => 'King\'s is one of the oldest and most prestigious universities in England, with particular strengths in humanities, law, and health sciences.',
                'programs' => ['Medicine', 'Law', 'Humanities', 'Dentistry', 'Psychiatry'],
                'popular_majors' => ['Law', 'Medicine', 'War Studies', 'English', 'History'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'London School of Economics (LSE)',
                'country_id' => $uk->id,
                'city' => 'London',
                'state' => 'England',
                'world_ranking' => 45,
                'country_ranking' => 7,
                'tuition_min' => 23330,
                'tuition_max' => 26184,
                'website' => 'https://www.lse.ac.uk',
                'established_year' => 1895,
                'type' => 'public',
                'acceptance_rate' => 8.9,
                'student_count' => 12330,
                'international_students' => 9234,
                'scholarships_available' => true,
                'application_fee' => 70,
                'description' => 'LSE is a specialist social science university with a global reputation for excellence in research and teaching.',
                'programs' => ['Economics', 'Politics', 'Law', 'Sociology', 'International Relations'],
                'popular_majors' => ['Economics', 'International Relations', 'Law', 'Accounting', 'Government'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'University of Manchester',
                'country_id' => $uk->id,
                'city' => 'Manchester',
                'state' => 'England',
                'world_ranking' => 32,
                'country_ranking' => 8,
                'tuition_min' => 25000,
                'tuition_max' => 46000,
                'website' => 'https://www.manchester.ac.uk',
                'established_year' => 1824,
                'type' => 'public',
                'acceptance_rate' => 56.0,
                'student_count' => 40490,
                'international_students' => 12345,
                'scholarships_available' => true,
                'application_fee' => 60,
                'description' => 'Manchester is a major British university with a proud history of achievement and an ambitious agenda for the future.',
                'programs' => ['Engineering', 'Business', 'Medicine', 'Arts', 'Sciences'],
                'popular_majors' => ['Business Management', 'Computer Science', 'Medicine', 'Engineering', 'Law'],
                'is_featured' => false,
                'is_active' => true,
            ],

            // Canada Universities
            [
                'name' => 'University of Toronto',
                'country_id' => $canada->id,
                'city' => 'Toronto',
                'state' => 'Ontario',
                'world_ranking' => 21,
                'country_ranking' => 1,
                'tuition_min' => 45690,
                'tuition_max' => 58160,
                'website' => 'https://www.utoronto.ca',
                'established_year' => 1827,
                'type' => 'public',
                'acceptance_rate' => 43.0,
                'student_count' => 91286,
                'international_students' => 23456,
                'scholarships_available' => true,
                'application_fee' => 150,
                'description' => 'The University of Toronto is Canada\'s leading institution of learning and research, with a global reputation.',
                'programs' => ['Engineering', 'Business', 'Medicine', 'Arts & Science', 'Computer Science'],
                'popular_majors' => ['Computer Science', 'Engineering Science', 'Life Sciences', 'Business', 'Psychology'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'University of British Columbia',
                'country_id' => $canada->id,
                'city' => 'Vancouver',
                'state' => 'British Columbia',
                'world_ranking' => 34,
                'country_ranking' => 2,
                'tuition_min' => 38946,
                'tuition_max' => 44802,
                'website' => 'https://www.ubc.ca',
                'established_year' => 1908,
                'type' => 'public',
                'acceptance_rate' => 52.0,
                'student_count' => 66247,
                'international_students' => 17234,
                'scholarships_available' => true,
                'application_fee' => 118,
                'description' => 'UBC is a global centre for research and teaching, consistently ranked among the top public universities in the world.',
                'programs' => ['Applied Science', 'Arts', 'Commerce', 'Science', 'Medicine'],
                'popular_majors' => ['Business', 'Psychology', 'Biology', 'Computer Science', 'Economics'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'McGill University',
                'country_id' => $canada->id,
                'city' => 'Montreal',
                'state' => 'Quebec',
                'world_ranking' => 31,
                'country_ranking' => 3,
                'tuition_min' => 20000,
                'tuition_max' => 51000,
                'website' => 'https://www.mcgill.ca',
                'established_year' => 1821,
                'type' => 'public',
                'acceptance_rate' => 46.0,
                'student_count' => 40067,
                'international_students' => 12345,
                'scholarships_available' => true,
                'application_fee' => 120,
                'description' => 'McGill is one of Canada\'s best-known institutions of higher learning and one of the leading universities in the world.',
                'programs' => ['Medicine', 'Law', 'Engineering', 'Management', 'Arts'],
                'popular_majors' => ['Psychology', 'Economics', 'Biology', 'Computer Science', 'Political Science'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'McMaster University',
                'country_id' => $canada->id,
                'city' => 'Hamilton',
                'state' => 'Ontario',
                'world_ranking' => 152,
                'country_ranking' => 4,
                'tuition_min' => 28393,
                'tuition_max' => 42190,
                'website' => 'https://www.mcmaster.ca',
                'established_year' => 1887,
                'type' => 'public',
                'acceptance_rate' => 58.0,
                'student_count' => 36000,
                'international_students' => 8234,
                'scholarships_available' => true,
                'application_fee' => 140,
                'description' => 'McMaster is one of Canada\'s most research-intensive universities, known for its medical school and problem-based learning.',
                'programs' => ['Health Sciences', 'Engineering', 'Business', 'Science', 'Social Sciences'],
                'popular_majors' => ['Health Sciences', 'Engineering', 'Business', 'Kinesiology', 'Life Sciences'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'University of Montreal',
                'country_id' => $canada->id,
                'city' => 'Montreal',
                'state' => 'Quebec',
                'world_ranking' => 116,
                'country_ranking' => 5,
                'tuition_min' => 20000,
                'tuition_max' => 24000,
                'website' => 'https://www.umontreal.ca',
                'established_year' => 1878,
                'type' => 'public',
                'acceptance_rate' => 57.0,
                'student_count' => 67200,
                'international_students' => 9876,
                'scholarships_available' => true,
                'application_fee' => 87,
                'description' => 'Université de Montréal is one of Canada\'s leading research universities, with strong programs in French.',
                'programs' => ['Medicine', 'Law', 'Arts', 'Sciences', 'Music'],
                'popular_majors' => ['Medicine', 'Law', 'Psychology', 'Business Administration', 'Computer Science'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'University of Alberta',
                'country_id' => $canada->id,
                'city' => 'Edmonton',
                'state' => 'Alberta',
                'world_ranking' => 110,
                'country_ranking' => 6,
                'tuition_min' => 26000,
                'tuition_max' => 30000,
                'website' => 'https://www.ualberta.ca',
                'established_year' => 1908,
                'type' => 'public',
                'acceptance_rate' => 58.0,
                'student_count' => 40000,
                'international_students' => 7654,
                'scholarships_available' => true,
                'application_fee' => 125,
                'description' => 'The University of Alberta is one of Canada\'s top research universities, with a broad range of programs.',
                'programs' => ['Engineering', 'Business', 'Science', 'Arts', 'Agriculture'],
                'popular_majors' => ['Engineering', 'Business', 'Nursing', 'Biological Sciences', 'Psychology'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'University of Waterloo',
                'country_id' => $canada->id,
                'city' => 'Waterloo',
                'state' => 'Ontario',
                'world_ranking' => 154,
                'country_ranking' => 7,
                'tuition_min' => 35000,
                'tuition_max' => 61000,
                'website' => 'https://uwaterloo.ca',
                'established_year' => 1957,
                'type' => 'public',
                'acceptance_rate' => 53.0,
                'student_count' => 42000,
                'international_students' => 8765,
                'scholarships_available' => true,
                'application_fee' => 125,
                'description' => 'Waterloo is Canada\'s most innovative university, known for its co-op program and strength in engineering and computer science.',
                'programs' => ['Engineering', 'Mathematics', 'Computer Science', 'Science', 'Arts'],
                'popular_majors' => ['Computer Science', 'Software Engineering', 'Mechatronics Engineering', 'Mathematics', 'Accounting'],
                'is_featured' => false,
                'is_active' => true,
            ],

            // Australia Universities
            [
                'name' => 'Australian National University',
                'country_id' => $australia->id,
                'city' => 'Canberra',
                'state' => 'Australian Capital Territory',
                'world_ranking' => 30,
                'country_ranking' => 1,
                'tuition_min' => 35000,
                'tuition_max' => 48000,
                'website' => 'https://www.anu.edu.au',
                'established_year' => 1946,
                'type' => 'public',
                'acceptance_rate' => 35.0,
                'student_count' => 25892,
                'international_students' => 7234,
                'scholarships_available' => true,
                'application_fee' => 100,
                'description' => 'ANU is Australia\'s national university, with a global reputation for research excellence.',
                'programs' => ['Arts & Social Sciences', 'Asia & Pacific', 'Business & Economics', 'Engineering', 'Science'],
                'popular_majors' => ['Politics', 'International Relations', 'Economics', 'Computer Science', 'Psychology'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'University of Melbourne',
                'country_id' => $australia->id,
                'city' => 'Melbourne',
                'state' => 'Victoria',
                'world_ranking' => 14,
                'country_ranking' => 2,
                'tuition_min' => 38000,
                'tuition_max' => 50000,
                'website' => 'https://www.unimelb.edu.au',
                'established_year' => 1853,
                'type' => 'public',
                'acceptance_rate' => 70.0,
                'student_count' => 51000,
                'international_students' => 18234,
                'scholarships_available' => true,
                'application_fee' => 100,
                'description' => 'The University of Melbourne is a leading public research university located in Melbourne, Australia.',
                'programs' => ['Arts', 'Business & Economics', 'Medicine', 'Science', 'Engineering'],
                'popular_majors' => ['Commerce', 'Biomedicine', 'Science', 'Arts', 'Design'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'University of Sydney',
                'country_id' => $australia->id,
                'city' => 'Sydney',
                'state' => 'New South Wales',
                'world_ranking' => 19,
                'country_ranking' => 3,
                'tuition_min' => 37000,
                'tuition_max' => 55000,
                'website' => 'https://www.sydney.edu.au',
                'established_year' => 1850,
                'type' => 'public',
                'acceptance_rate' => 30.0,
                'student_count' => 73000,
                'international_students' => 27234,
                'scholarships_available' => true,
                'application_fee' => 125,
                'description' => 'The University of Sydney is one of Australia\'s leading universities and is consistently ranked among the top universities in the world.',
                'programs' => ['Arts & Social Sciences', 'Business', 'Engineering', 'Medicine & Health', 'Science'],
                'popular_majors' => ['Business', 'Engineering', 'Arts', 'Science', 'Medicine'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'University of New South Wales (UNSW)',
                'country_id' => $australia->id,
                'city' => 'Sydney',
                'state' => 'New South Wales',
                'world_ranking' => 43,
                'country_ranking' => 4,
                'tuition_min' => 34000,
                'tuition_max' => 51000,
                'website' => 'https://www.unsw.edu.au',
                'established_year' => 1949,
                'type' => 'public',
                'acceptance_rate' => 51.0,
                'student_count' => 59000,
                'international_students' => 21234,
                'scholarships_available' => true,
                'application_fee' => 100,
                'description' => 'UNSW Sydney is one of Australia\'s leading research and teaching universities, and a founding member of the Group of Eight.',
                'programs' => ['Engineering', 'Business', 'Science', 'Arts & Social Sciences', 'Medicine'],
                'popular_majors' => ['Engineering', 'Business', 'Computer Science', 'Commerce', 'Science'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'University of Queensland',
                'country_id' => $australia->id,
                'city' => 'Brisbane',
                'state' => 'Queensland',
                'world_ranking' => 43,
                'country_ranking' => 5,
                'tuition_min' => 32000,
                'tuition_max' => 45000,
                'website' => 'https://www.uq.edu.au',
                'established_year' => 1909,
                'type' => 'public',
                'acceptance_rate' => 54.0,
                'student_count' => 54600,
                'international_students' => 19234,
                'scholarships_available' => true,
                'application_fee' => 100,
                'description' => 'UQ is one of Australia\'s leading teaching and research universities, with a strong focus on delivering knowledge leadership.',
                'programs' => ['Business', 'Engineering', 'Medicine', 'Science', 'Health'],
                'popular_majors' => ['Business Management', 'Engineering', 'Biomedical Science', 'Psychology', 'Exercise Science'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Monash University',
                'country_id' => $australia->id,
                'city' => 'Melbourne',
                'state' => 'Victoria',
                'world_ranking' => 42,
                'country_ranking' => 6,
                'tuition_min' => 33000,
                'tuition_max' => 48000,
                'website' => 'https://www.monash.edu',
                'established_year' => 1958,
                'type' => 'public',
                'acceptance_rate' => 40.0,
                'student_count' => 86000,
                'international_students' => 26234,
                'scholarships_available' => true,
                'application_fee' => 100,
                'description' => 'Monash is a leading Australian university with a global reputation for excellence in teaching and research.',
                'programs' => ['Arts', 'Business & Economics', 'Education', 'Engineering', 'Medicine'],
                'popular_majors' => ['Business', 'Engineering', 'Education', 'Medicine', 'Information Technology'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'University of Western Australia',
                'country_id' => $australia->id,
                'city' => 'Perth',
                'state' => 'Western Australia',
                'world_ranking' => 90,
                'country_ranking' => 7,
                'tuition_min' => 31000,
                'tuition_max' => 41000,
                'website' => 'https://www.uwa.edu.au',
                'established_year' => 1911,
                'type' => 'public',
                'acceptance_rate' => 69.0,
                'student_count' => 24000,
                'international_students' => 6234,
                'scholarships_available' => true,
                'application_fee' => 100,
                'description' => 'UWA is a member of the prestigious Group of Eight research-intensive universities in Australia.',
                'programs' => ['Arts', 'Business', 'Science', 'Engineering', 'Medicine'],
                'popular_majors' => ['Commerce', 'Biomedical Science', 'Engineering', 'Psychology', 'Data Science'],
                'is_featured' => false,
                'is_active' => true,
            ],

            // Germany Universities
            [
                'name' => 'Technical University of Munich',
                'country_id' => $germany->id,
                'city' => 'Munich',
                'state' => 'Bavaria',
                'world_ranking' => 37,
                'country_ranking' => 1,
                'tuition_min' => 0,
                'tuition_max' => 258,
                'website' => 'https://www.tum.de',
                'established_year' => 1868,
                'type' => 'public',
                'acceptance_rate' => 8.0,
                'student_count' => 44000,
                'international_students' => 13234,
                'scholarships_available' => true,
                'application_fee' => 0,
                'description' => 'TUM is one of Europe\'s top universities in engineering, science, and technology with a strong entrepreneurial culture.',
                'programs' => ['Engineering', 'Natural Sciences', 'Life Sciences', 'Medicine', 'Management'],
                'popular_majors' => ['Mechanical Engineering', 'Computer Science', 'Physics', 'Electrical Engineering', 'Mathematics'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Ludwig Maximilian University of Munich',
                'country_id' => $germany->id,
                'city' => 'Munich',
                'state' => 'Bavaria',
                'world_ranking' => 54,
                'country_ranking' => 2,
                'tuition_min' => 0,
                'tuition_max' => 258,
                'website' => 'https://www.lmu.de',
                'established_year' => 1472,
                'type' => 'public',
                'acceptance_rate' => 10.0,
                'student_count' => 50000,
                'international_students' => 7654,
                'scholarships_available' => true,
                'application_fee' => 0,
                'description' => 'LMU Munich is one of Europe\'s premier academic and research institutions, with over 500 years of tradition.',
                'programs' => ['Humanities', 'Law', 'Business', 'Medicine', 'Natural Sciences'],
                'popular_majors' => ['Medicine', 'Law', 'Business Administration', 'Psychology', 'Biology'],
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Heidelberg University',
                'country_id' => $germany->id,
                'city' => 'Heidelberg',
                'state' => 'Baden-Württemberg',
                'world_ranking' => 64,
                'country_ranking' => 3,
                'tuition_min' => 0,
                'tuition_max' => 1500,
                'website' => 'https://www.uni-heidelberg.de',
                'established_year' => 1386,
                'type' => 'public',
                'acceptance_rate' => 19.0,
                'student_count' => 31000,
                'international_students' => 6234,
                'scholarships_available' => true,
                'application_fee' => 0,
                'description' => 'Heidelberg is Germany\'s oldest university and one of Europe\'s most research-intensive institutions.',
                'programs' => ['Medicine', 'Law', 'Theology', 'Natural Sciences', 'Humanities'],
                'popular_majors' => ['Medicine', 'Law', 'Molecular Biotechnology', 'Psychology', 'Economics'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Humboldt University of Berlin',
                'country_id' => $germany->id,
                'city' => 'Berlin',
                'state' => 'Berlin',
                'world_ranking' => 117,
                'country_ranking' => 4,
                'tuition_min' => 0,
                'tuition_max' => 315,
                'website' => 'https://www.hu-berlin.de',
                'established_year' => 1810,
                'type' => 'public',
                'acceptance_rate' => 18.0,
                'student_count' => 35000,
                'international_students' => 6789,
                'scholarships_available' => true,
                'application_fee' => 0,
                'description' => 'Humboldt University is one of Berlin\'s oldest universities, known for its research and innovation.',
                'programs' => ['Humanities', 'Law', 'Life Sciences', 'Natural Sciences', 'Theology'],
                'popular_majors' => ['Law', 'Business Administration', 'Psychology', 'Biology', 'Computer Science'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Free University of Berlin',
                'country_id' => $germany->id,
                'city' => 'Berlin',
                'state' => 'Berlin',
                'world_ranking' => 127,
                'country_ranking' => 5,
                'tuition_min' => 0,
                'tuition_max' => 315,
                'website' => 'https://www.fu-berlin.de',
                'established_year' => 1948,
                'type' => 'public',
                'acceptance_rate' => 15.0,
                'student_count' => 33000,
                'international_students' => 7123,
                'scholarships_available' => true,
                'application_fee' => 0,
                'description' => 'FU Berlin is one of Germany\'s leading research universities with a strong international focus.',
                'programs' => ['Humanities', 'Social Sciences', 'Natural Sciences', 'Medicine', 'Law'],
                'popular_majors' => ['Political Science', 'Medicine', 'Psychology', 'Biology', 'Law'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'RWTH Aachen University',
                'country_id' => $germany->id,
                'city' => 'Aachen',
                'state' => 'North Rhine-Westphalia',
                'world_ranking' => 106,
                'country_ranking' => 6,
                'tuition_min' => 0,
                'tuition_max' => 285,
                'website' => 'https://www.rwth-aachen.de',
                'established_year' => 1870,
                'type' => 'public',
                'acceptance_rate' => 10.0,
                'student_count' => 47000,
                'international_students' => 12345,
                'scholarships_available' => true,
                'application_fee' => 0,
                'description' => 'RWTH Aachen is one of Germany\'s leading technical universities with strong industry partnerships.',
                'programs' => ['Engineering', 'Natural Sciences', 'Medicine', 'Business & Economics'],
                'popular_majors' => ['Mechanical Engineering', 'Electrical Engineering', 'Computer Science', 'Business Engineering', 'Physics'],
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'University of Freiburg',
                'country_id' => $germany->id,
                'city' => 'Freiburg',
                'state' => 'Baden-Württemberg',
                'world_ranking' => 172,
                'country_ranking' => 7,
                'tuition_min' => 0,
                'tuition_max' => 1500,
                'website' => 'https://www.uni-freiburg.de',
                'established_year' => 1457,
                'type' => 'public',
                'acceptance_rate' => 22.0,
                'student_count' => 25000,
                'international_students' => 5432,
                'scholarships_available' => true,
                'application_fee' => 0,
                'description' => 'The University of Freiburg is one of Germany\'s oldest and most renowned universities.',
                'programs' => ['Medicine', 'Law', 'Natural Sciences', 'Humanities', 'Engineering'],
                'popular_majors' => ['Medicine', 'Law', 'Biology', 'Forestry', 'Psychology'],
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        foreach ($universities as $university) {
            University::create($university);
        }

        $this->command->info('Successfully seeded '.count($universities).' universities!');
    }
}
