<?php

namespace Database\Seeders;

use App\Models\VisaRequirement;
use Illuminate\Database\Seeder;

class VisaRequirementSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $requirements = [
            // USA Visas
            [
                'country' => 'United States',
                'country_code' => 'USA',
                'visa_type' => 'tourist',
                'visa_category' => 'B1/B2',
                'required_documents' => ['Passport', 'Photo (2x2)', 'Bank Statement (6 months)', 'Travel Itinerary', 'Hotel Reservation', 'Return Ticket'],
                'processing_time' => '3-5 weeks',
                'validity_period' => '10 years (multiple entry)',
                'is_template' => true,
                'general_requirements' => 'Valid passport with at least 6 months validity. Proof of financial stability. Proof of ties to home country.',
                'eligibility_criteria' => 'No criminal record. Ability to financially support travel. Strong ties to Bangladesh.',
                'important_notes' => 'Interview at US Embassy is mandatory. Bring original documents to interview.',
                'min_bank_balance' => 500000,
                'bank_statement_months' => 6,
                'government_fee' => 16000,
                'service_fee' => 5000,
                'processing_fee_standard' => 3000,
                'processing_fee_express' => 6000,
                'processing_fee_urgent' => 10000,
                'currency' => 'BDT',
                'processing_days_standard' => 21,
                'processing_days_express' => 14,
                'processing_days_urgent' => 7,
                'interview_required' => true,
                'interview_details' => 'Face-to-face interview at US Embassy Dhaka. Appointment booking required online.',
                'biometrics_required' => true,
                'biometrics_details' => 'Fingerprints and photo taken during interview.',
                'application_method' => 'online',
                'embassy_website' => 'https://bd.usembassy.gov',
                'tips_for_applicants' => ['Be honest during interview', 'Dress professionally', 'Bring original documents', 'Show strong ties to Bangladesh'],
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'country' => 'United States',
                'country_code' => 'USA',
                'visa_type' => 'student',
                'visa_category' => 'F1',
                'required_documents' => ['Passport', 'Photo', 'I-20 Form from University', 'Proof of Funds', 'Admission Letter', 'Bank Statement', 'Academic Transcripts', 'TOEFL/IELTS Scores'],
                'processing_time' => '2-4 weeks',
                'validity_period' => 'Duration of study',
                'general_requirements' => 'Valid admission to US university. Proof of financial support for tuition and living expenses.',
                'min_bank_balance' => 3000000,
                'bank_statement_months' => 6,
                'government_fee' => 16000,
                'service_fee' => 8000,
                'processing_fee_standard' => 5000,
                'processing_fee_express' => 9000,
                'processing_fee_urgent' => 15000,
                'processing_days_standard' => 21,
                'processing_days_express' => 14,
                'processing_days_urgent' => 7,
                'interview_required' => true,
                'biometrics_required' => true,
                'is_active' => true,
                'sort_order' => 2,
            ],

            // UK Visas
            [
                'country' => 'United Kingdom',
                'country_code' => 'GBR',
                'visa_type' => 'tourist',
                'visa_category' => 'Standard Visitor',
                'required_documents' => ['Passport', 'Photo', 'Bank Statement (3 months)', 'Travel Itinerary', 'Hotel Booking', 'Employment Letter'],
                'processing_time' => '3 weeks',
                'validity_period' => '6 months',
                'general_requirements' => 'Passport valid for at least 6 months. Proof of funds. Travel insurance.',
                'min_bank_balance' => 300000,
                'bank_statement_months' => 3,
                'government_fee' => 10500,
                'service_fee' => 4000,
                'processing_fee_standard' => 2500,
                'processing_fee_express' => 5000,
                'processing_fee_urgent' => 8000,
                'processing_days_standard' => 15,
                'processing_days_express' => 7,
                'processing_days_urgent' => 3,
                'interview_required' => false,
                'biometrics_required' => true,
                'biometrics_details' => 'Biometrics at VFS Global center in Dhaka.',
                'application_method' => 'online',
                'embassy_website' => 'https://www.gov.uk/apply-uk-visa',
                'important_notes' => 'NHS surcharge may apply for stays over 6 months.',
                'is_active' => true,
                'sort_order' => 3,
            ],

            // Canada Visas
            [
                'country' => 'Canada',
                'country_code' => 'CAN',
                'visa_type' => 'tourist',
                'visa_category' => 'Visitor Visa',
                'required_documents' => ['Passport', 'Photo', 'Bank Statement', 'Travel Itinerary', 'Invitation Letter (if applicable)', 'Employment Letter'],
                'processing_time' => '2-4 weeks',
                'validity_period' => 'Up to 10 years',
                'general_requirements' => 'Valid passport. Proof of financial support. Travel history.',
                'min_bank_balance' => 250000,
                'bank_statement_months' => 6,
                'government_fee' => 10000,
                'service_fee' => 3500,
                'processing_fee_standard' => 2000,
                'processing_fee_express' => 4000,
                'processing_fee_urgent' => 7000,
                'processing_days_standard' => 20,
                'processing_days_express' => 10,
                'processing_days_urgent' => 5,
                'interview_required' => false,
                'biometrics_required' => true,
                'biometrics_details' => 'Biometrics collection at VFS Global.',
                'application_method' => 'online',
                'embassy_website' => 'https://www.canada.ca/en/immigration-refugees-citizenship.html',
                'is_active' => true,
                'sort_order' => 4,
            ],

            // Australia Visa
            [
                'country' => 'Australia',
                'country_code' => 'AUS',
                'visa_type' => 'tourist',
                'visa_category' => 'Visitor Visa (600)',
                'required_documents' => ['Passport', 'Photo', 'Bank Statement', 'Travel Plan', 'Hotel Bookings', 'Employment Letter'],
                'processing_time' => '2-3 weeks',
                'validity_period' => '3, 6, or 12 months',
                'general_requirements' => 'Passport valid for at least 6 months. Financial capacity. Health insurance.',
                'min_bank_balance' => 400000,
                'bank_statement_months' => 6,
                'government_fee' => 15000,
                'service_fee' => 4500,
                'processing_fee_standard' => 3000,
                'processing_fee_express' => 6000,
                'processing_fee_urgent' => 10000,
                'processing_days_standard' => 18,
                'processing_days_express' => 10,
                'processing_days_urgent' => 5,
                'interview_required' => false,
                'biometrics_required' => true,
                'application_method' => 'online',
                'embassy_website' => 'https://immi.homeaffairs.gov.au',
                'is_active' => true,
                'sort_order' => 5,
            ],

            // Schengen Visa (for European countries)
            [
                'country' => 'Schengen',
                'country_code' => 'SCH',
                'visa_type' => 'tourist',
                'visa_category' => 'Short Stay',
                'required_documents' => ['Passport', 'Photo', 'Travel Insurance (€30,000 coverage)', 'Hotel Bookings', 'Flight Tickets', 'Bank Statement'],
                'processing_time' => '2-3 weeks',
                'validity_period' => '90 days within 180 days',
                'general_requirements' => 'Passport valid for at least 3 months beyond stay. Travel insurance mandatory.',
                'min_bank_balance' => 200000,
                'bank_statement_months' => 3,
                'government_fee' => 8000,
                'service_fee' => 3000,
                'processing_fee_standard' => 2000,
                'processing_fee_express' => 4000,
                'processing_fee_urgent' => 6000,
                'processing_days_standard' => 15,
                'processing_days_express' => 7,
                'processing_days_urgent' => 3,
                'interview_required' => true,
                'interview_details' => 'Interview at respective embassy/consulate.',
                'biometrics_required' => true,
                'application_method' => 'online/in-person',
                'is_active' => true,
                'sort_order' => 6,
            ],

            // Singapore Visa
            [
                'country' => 'Singapore',
                'country_code' => 'SGP',
                'visa_type' => 'tourist',
                'visa_category' => 'Tourist Visa',
                'required_documents' => ['Passport', 'Photo', 'Bank Statement', 'Hotel Booking', 'Flight Tickets'],
                'processing_time' => '3-5 working days',
                'validity_period' => '30-90 days',
                'general_requirements' => 'Valid passport with at least 6 months validity. Proof of sufficient funds.',
                'min_bank_balance' => 150000,
                'bank_statement_months' => 3,
                'government_fee' => 3000,
                'service_fee' => 2000,
                'processing_fee_standard' => 1000,
                'processing_fee_express' => 2000,
                'processing_fee_urgent' => 3000,
                'processing_days_standard' => 5,
                'processing_days_express' => 3,
                'processing_days_urgent' => 1,
                'interview_required' => false,
                'biometrics_required' => false,
                'application_method' => 'online',
                'embassy_website' => 'https://www.mfa.gov.sg',
                'is_active' => true,
                'sort_order' => 7,
            ],

            // Malaysia Visa
            [
                'country' => 'Malaysia',
                'country_code' => 'MYS',
                'visa_type' => 'tourist',
                'visa_category' => 'eVisa',
                'required_documents' => ['Passport', 'Photo', 'Flight Tickets', 'Hotel Booking'],
                'processing_time' => '2-3 working days',
                'validity_period' => '3 months (single entry)',
                'general_requirements' => 'Passport valid for at least 6 months. Return flight ticket.',
                'min_bank_balance' => 100000,
                'bank_statement_months' => 3,
                'government_fee' => 2500,
                'service_fee' => 1500,
                'processing_fee_standard' => 800,
                'processing_fee_express' => 1500,
                'processing_fee_urgent' => 2500,
                'processing_days_standard' => 3,
                'processing_days_express' => 2,
                'processing_days_urgent' => 1,
                'interview_required' => false,
                'biometrics_required' => false,
                'application_method' => 'online',
                'embassy_website' => 'https://www.visa.com.my',
                'is_active' => true,
                'sort_order' => 8,
            ],
        ];

        foreach ($requirements as $requirement) {
            VisaRequirement::updateOrCreate(
                [
                    'country' => $requirement['country'],
                    'visa_type' => $requirement['visa_type'],
                ],
                $requirement
            );
        }

        $this->command->info('✅ Visa requirements seeded successfully!');
    }
}
